---
sidebar: sidebar 
permalink: concept-data-services.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Connector ist die NetApp Software, die in Ihrem Cloud-Netzwerk oder Ihrem On-Premises-Netzwerk ausgeführt wird. Sie führt die Aktionen aus, die BlueXP für das Management der Dateninfrastruktur benötigt. Der Connector fragt fortlaufend die BlueXP SaaS-Ebene nach möglichen Aktionen ab. Für den Einstieg in BlueXP benötigen Sie keinen Connector, aber Sie müssen einen Connector erstellen, mit dem Sie alle BlueXP Funktionen und Services nutzen können. 
---
= Weitere Informationen zu BlueXP  Services
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit NetApp BlueXP steht Ihrem Unternehmen eine einzelne Managementplattform zur Verfügung, mit der Sie Ihre Daten über Ihre On-Premises- und Cloud-Umgebungen hinweg erstellen, schützen und regeln können.

Sie können wählen, ob Sie den BlueXP  SaaS Service (Standardmodus) verwenden, BlueXP  in Ihrer Cloud-Umgebung mit beschränktem Modus ausführen oder ihn in Ihrem eigenen lokalen Datacenter (privater Modus) installieren. Für welche Umgebung auch immer Sie sich entscheiden: Sie profitieren von zentralisiertem Management und zusätzlichen Datenservices, die für eine stabile und sichere Storage-Ressourcen sorgen.

Der von Ihnen gewählte Modus legt fest, welche Services Ihnen zur Verfügung stehen und welche Storage-Ressourcen Sie verwalten können.

Vergleichen Sie zunächst die verschiedenen Storage-Ressourcen, die die einzelnen Modi unterstützen, zusammen mit verfügbaren Daten-Services, um Ihnen bei der Entscheidung zu helfen, was für Ihre Unternehmensanforderungen am sinnvollsten ist.



== Datenservices

Die folgende Tabelle gibt an, welche Datenservices in den einzelnen Bereitstellungsmodi verfügbar sind, ob Sie ein Abonnement benötigen und wann Sie ein Support-Konto benötigen.

[NOTE]
====
*Connectors* die Spalte Connector in der Tabelle gibt an, wann Sie einen Connector für den Standardmodus benötigen. Wenn Sie BlueXP  im eingeschränkten oder privaten Modus verwenden, benötigen Sie immer einen Connector.

====
[cols="24,19,19,19,19"]
|===
|  | Support-Konto erforderlich | Connector Erforderlich | Abonnement erforderlich | Verfügbarkeit des Modus 


| Meldungen | Ja. | Ja. | Nein | Alle 


| Backup und Recovery | Ja. | Ja. | Ja. | Standard, Eingeschränkt 


| Klassifizierung | Ja. | Nein | Nein | Alle 


| Kopieren und Synchronisieren | Nein | Nein | Ja. |  


| Digitaler Berater | Ja. | Nein | Nein | Alle 


| Digitale Brieftasche | Ja. | Nein* | Nein | Alle 


| Disaster Recovery | Nein | Ja. | Ja. | Standard, Eingeschränkt 


| Wirtschaftliche Effizienz | Ja. | Ja. | Nein |  


| Operative Ausfallsicherheit | Ja. | Ja* | Nein |  


| Schutz durch Ransomware | Nein | Ja. | Nein | Standard 


| Replizierung | Nein | Nein* | Nein | Standard, Eingeschränkt 


| Software-Updates | Ja. | Nein | Nein | Alle 


| Support-Case-Management | Ja. | Nein | Nein | Alle 


| Tiering | Nein | Nein* | Ja. | Standard 


| Volume-Caching | Nein | Nein | Nein | Standard 
|===


== NetApp Storage durchführt

Sie können einen Großteil Ihrer NetApp Storage-Ressourcen direkt von BlueXP  aus managen. So können Sie alle Ressourcen von derselben Applikation aus anzeigen.

In der folgenden Tabelle ist aufgeführt, welche Storage-Ressourcen Sie in den einzelnen Implementierungsmodi managen können und ob Sie einen Connector oder ein Abonnement benötigen.

[NOTE]
====
*Connectors* die Spalte Connector in der Tabelle gibt an, wann Sie einen Connector für den Standardmodus benötigen. Wenn Sie BlueXP  im eingeschränkten oder privaten Modus verwenden, benötigen Sie immer einen Connector.

====
[cols="24,19,19,19,19"]
|===
|  | Support-Konto erforderlich | Connector Erforderlich | Abonnement erforderlich | Verfügbarkeit des Modus 


| Amazon FSX für NetApp ONTAP | Ja. | Nein^1^ | Ja. | Standard 


| Amazon S3 Storage | Ja. | Nein | Ja. | Standard 


| Azure Blob Storage | Ja. | Nein | Nein | Standard 


| Azure NetApp Dateien | Nein | Nein^2^ | Ja. | Standard, Eingeschränkt 


| Cloud Volumes ONTAP | Ja. | Ja. | Ja. | Standard, Eingeschränkt 


| Cloud Volumes Service für Google Cloud | Nein | Nein | Ja? | Standard 


| E-Series Systeme | Nein | Ja. | Nein | Standard 


| Google Cloud Storage | Nein | Ja. | Ja? | Standard 


| On-Premises ONTAP Cluster | Ja. | Nein^3^ | Nein | Alle 


| StorageGRID | Ja. | Ja. | Nein | Standard, Eingeschränkt 
|===
^1^ für einige Aktionen ist ein Konnektor oder ein BlueXP  Workload Factory Link erforderlich. https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["Erfahren Sie, welche Aktionen einen Konnektor oder eine Verknüpfung erfordern"^]

^2^ ein Connector ist zwar nicht für die Einrichtung und Verwaltung von Azure NetApp Files erforderlich, jedoch ist ein Connector erforderlich, wenn Sie zum Scannen von Azure NetApp Files-Daten die BlueXP -Klassifizierung verwenden möchten.

^3^ Obwohl für die direkte Erkennung eines lokalen ONTAP-Clusters kein Connector erforderlich ist, ist ein Connector erforderlich, wenn Sie von zusätzlichen BlueXP -Funktionen profitieren möchten. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Weitere Informationen zu den Wiederauffindungs- und Managementoptionen für lokale ONTAP Cluster"^]
