---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Connector ist die NetApp Software, die in Ihrem Cloud-Netzwerk oder Ihrem On-Premises-Netzwerk ausgeführt wird. Sie führt die Aktionen aus, die BlueXP für das Management der Dateninfrastruktur benötigt. Der Connector fragt fortlaufend die BlueXP SaaS-Ebene nach möglichen Aktionen ab. Für den Einstieg in BlueXP benötigen Sie keinen Connector, aber Sie müssen einen Connector erstellen, mit dem Sie alle BlueXP Funktionen und Services nutzen können. 
---
= Erfahren Sie mehr über Steckverbinder
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A _Connector_ ist die NetApp Software, die in Ihrem Cloud-Netzwerk oder Ihrem On-Premises-Netzwerk ausgeführt wird. Sie führt die Aktionen aus, die BlueXP für das Management der Dateninfrastruktur benötigt. Der Connector fragt fortlaufend die SaaS-Ebene (Software as a Service) von BlueXP  ab, ob erforderliche Aktionen ausgeführt werden müssen. Für den Einstieg in BlueXP benötigen Sie keinen Connector, aber Sie müssen einen Connector erstellen, mit dem Sie alle BlueXP Funktionen und Services nutzen können.



== Was Sie ohne einen Connector tun können

Für den Einstieg in BlueXP ist kein Connector erforderlich. Sie können mehrere Funktionen und Services in BlueXP nutzen, ohne jemals einen Connector zu erstellen.

Ohne Connector können Sie die folgenden BlueXP Funktionen und Services nutzen:

* Amazon FSX für NetApp ONTAP
+
Für einige Aktionen ist eine Verknüpfung für den Connector oder die Werkseinstellungen des BlueXP -Workloads erforderlich. https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["Erfahren Sie, welche Aktionen einen Konnektor oder eine Verknüpfung erfordern"^]

* Automatisierungsskatalog
* Azure NetApp Dateien
+
Für die Einrichtung und das Management von Azure NetApp Files ist kein Connector erforderlich, aber für die Suche nach Azure NetApp Files Daten ist ein Connector erforderlich.

* Cloud Volumes Service für Google Cloud
* Kopieren und Synchronisieren
* Digitaler Berater
* Digital Wallet (nur Lizenzen, Abonnement-Überwachung erfordert einen Connector)
+
In fast allen Fällen können Sie der Digital Wallet ohne Connector eine Lizenz hinzufügen.

+
Zum Hinzufügen einer Lizenz zur digitalen Brieftasche ist nur ein Connector erforderlich, wenn Cloud Volumes ONTAP _Node-based_ Lizenzen verwendet werden. In diesem Fall ist ein Connector erforderlich, da die Daten aus den auf Cloud Volumes ONTAP-Systemen installierten Lizenzen stammen.

* Direkte Erkennung von ONTAP Clustern vor Ort
+
Ein Connector ist zwar nicht für die direkte Erkennung eines lokalen ONTAP-Clusters erforderlich, jedoch ist ein Connector erforderlich, wenn Sie zusätzliche BlueXP-Funktionen nutzen möchten.

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Weitere Informationen zu den Wiederauffindungs- und Managementoptionen für lokale ONTAP Cluster"^]

* Software-Updates
* Nachhaltigkeit
* Arbeitslast Fabrik




== Wenn ein Stecker erforderlich ist

Wenn Sie BlueXP im Standardmodus verwenden, ist für die folgenden Funktionen und Services in BlueXP ein Connector erforderlich:

* Meldungen
* Managementfunktionen von Amazon FSX für ONTAP
* Amazon S3 Storage
* Azure Blob Storage
* Backup und Recovery
* Klassifizierung
* Cloud Volumes ONTAP
* Disaster Recovery
* E-Series Systeme
* Wirtschaftliche Effizienz ^1^
* Google Cloud Storage Buckets
* On-Premises-ONTAP-Cluster-Integration in BlueXP-Datenservices
* Ausfallsicherheit der Betriebsabläufe ^1^
* Schutz durch Ransomware
* StorageGRID Systeme
* Tiering
* Volume-Caching


^1^ während Sie ohne Connector auf diese Dienste zugreifen können, ist ein Connector erforderlich, um Aktionen von den Diensten zu initiieren.

Ein Connector ist erforderlich, um BlueXP im eingeschränkten Modus oder im privaten Modus zu verwenden.



== Die Anschlüsse müssen jederzeit betriebsbereit sein

Anschlüsse sind ein grundlegender Bestandteil der Service-Architektur von BlueXP. Es liegt in Ihrer Verantwortung sicherzustellen, dass die entsprechenden Steckverbinder jederzeit betriebsbereit und zugänglich sind. Während der Service darauf ausgelegt ist, kurze Ausfälle der Connector-Verfügbarkeit zu überwinden, müssen Sie bei Bedarf sofort Maßnahmen ergreifen, um Infrastrukturausfälle zu beheben.

Diese Dokumentation unterliegt der EULA. Wenn das Produkt nicht in Übereinstimmung mit der Dokumentation betrieben wird, können die Funktionalität und der Betrieb des Produkts sowie Ihre Rechte im Rahmen der EULA beeinträchtigt werden.



== Unterstützte Standorte

Ein Connector wird an folgenden Stellen unterstützt:

* Amazon Web Services
* Microsoft Azure
+
Ein Connector in Azure sollte in derselben Azure-Region wie die von ihm gemanagten Cloud Volumes ONTAP-Systeme oder in der für die Cloud Volumes ONTAP-Systeme bereitgestellt https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure Region Paar"^] werden. Diese Anforderung sorgt dafür, dass eine Azure Private Link-Verbindung zwischen Cloud Volumes ONTAP und ihren zugehörigen Storage-Konten verwendet wird. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Erfahren Sie, wie Cloud Volumes ONTAP einen privaten Azure Link nutzt"^]

* Google Cloud
+
Wenn Sie BlueXP Services in Verbindung mit Google Cloud nutzen möchten, müssen Sie einen Connector verwenden, der in Google Cloud ausgeführt wird.

* Vor Ort




== Kommunikation mit Cloud-Providern

Der Connector verwendet TLS 1.2 für die gesamte Kommunikation zu AWS, Azure und Google Cloud.



== Eingeschränkter Modus und privater Modus

Um BlueXP im eingeschränkten oder privaten Modus zu verwenden, starten Sie mit BlueXP. Installieren Sie dazu den Connector und greifen dann auf die Benutzeroberfläche zu, die lokal auf dem Connector ausgeführt wird.

link:concept-modes.html["Weitere Informationen zu BlueXP Implementierungsmodi"].



== So erstellen Sie einen Konnektor

Sie können einen Connector direkt von BlueXP , vom Marktplatz Ihres Cloud-Providers oder durch manuelle Installation der Software auf Ihrem eigenen Linux-Host erstellen. Der Einstieg hängt davon ab, ob Sie BlueXP im Standardmodus, im eingeschränkten Modus oder im privaten Modus nutzen.

* link:concept-modes.html["Weitere Informationen zu BlueXP Implementierungsmodi"]
* link:task-quick-start-standard-mode.html["Einstieg in BlueXP im Standardmodus"]
* link:task-quick-start-restricted-mode.html["Einstieg in BlueXP im eingeschränkten Modus"]
* link:task-quick-start-private-mode.html["Starten Sie mit BlueXP im privaten Modus"]




== Berechtigungen

Um den Connector direkt aus BlueXP zu erstellen, sind spezielle Berechtigungen erforderlich, für die Connector-Instanz selbst sind weitere Berechtigungen erforderlich. Wenn Sie den Connector in AWS oder Azure direkt aus BlueXP erstellen, erstellt BlueXP den Connector mit den entsprechenden Berechtigungen.

Wenn Sie BlueXP im Standardmodus verwenden, hängt die Art und Weise, wie Sie Berechtigungen bereitstellen, davon ab, wie Sie den Connector erstellen möchten.

Weitere Informationen zum Einrichten von Berechtigungen finden Sie unter:

* Standardmodus
+
** link:concept-install-options-aws.html["Installationsoptionen für Konnektoren in AWS"]
** link:concept-install-options-azure.html["Optionen für die Connector-Installation in Azure"]
** link:concept-install-options-google.html["Connector-Installationsoptionen in Google Cloud"]
** link:task-install-connector-on-prem.html#step-4-set-up-cloud-permissions["Cloud-Berechtigungen für On-Premises-Implementierungen einrichten"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Richten Sie Berechtigungen für den eingeschränkten Modus ein"]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["Richten Sie Berechtigungen für den privaten Modus ein"]


Auf den folgenden Seiten können Sie die genauen Berechtigungen anzeigen, die der Connector für den täglichen Betrieb benötigt:

* link:reference-permissions-aws.html["Erfahren Sie, wie der Connector AWS-Berechtigungen nutzt"]
* link:reference-permissions-azure.html["Erfahren Sie, wie der Connector Azure-Berechtigungen nutzt"]
* link:reference-permissions-gcp.html["Erfahren Sie, wie der Connector Google Cloud-Berechtigungen nutzt"]


Es liegt in Ihrer Verantwortung, die Connector-Richtlinien zu aktualisieren, wenn in nachfolgenden Versionen neue Berechtigungen hinzugefügt werden. Wenn neue Berechtigungen erforderlich sind, werden diese in den Versionshinweisen aufgeführt.



== Connector-Upgrades

Wir aktualisieren die Connector-Software in der Regel jeden Monat, um neue Funktionen einzuführen und Stabilitätsverbesserungen zu ermöglichen. Während die meisten Dienste und Funktionen der BlueXP -Plattform über SaaS-basierte Software angeboten werden, sind einige Funktionen von der Version des Connectors abhängig. Dazu gehören Cloud Volumes ONTAP-Management, On-Premises-ONTAP-Cluster-Management, Einstellungen und Hilfe.

Wenn Sie BlueXP im Standardmodus oder im eingeschränkten Modus verwenden, aktualisiert der Connector seine Software automatisch auf die neueste Version, sofern er über ausgehenden Internetzugang verfügt, um das Softwareupdate zu erhalten. Wenn Sie BlueXP im privaten Modus nutzen, müssen Sie den Connector manuell aktualisieren.

link:task-upgrade-connector.html["Erfahren Sie, wie Sie die Connector-Software manuell aktualisieren, wenn Sie den privaten Modus verwenden"].



== Betriebssystem- und VM-Wartung

Die Wartung des Betriebssystems auf dem Connector-Host liegt in Ihrer Verantwortung (des Kunden). Beispielsweise sollten Sie (Kunde) Sicherheitsupdates für das Betriebssystem auf dem Connector-Host anwenden, indem Sie die Standardverfahren Ihres Unternehmens für die Betriebssystemverteilung befolgen.

Beachten Sie, dass Sie (Kunde) keine Dienste auf dem Connector-Host anhalten müssen, wenn Sie kleinere Sicherheitsupdates anwenden.

Wenn Sie (Kunde) die Connector VM anhalten und dann starten müssen, sollten Sie dies von der Konsole Ihres Cloud-Providers oder mithilfe der Standardverfahren für das On-Premises-Management tun.

<<Die Anschlüsse müssen jederzeit betriebsbereit sein,Beachten Sie, dass der Connector jederzeit betriebsbereit sein muss>>.



== Mehrere Arbeitsumgebungen und Steckverbinder

Ein Connector kann mehrere Arbeitsumgebungen in BlueXP verwalten. Die maximale Anzahl von Arbeitsumgebungen, die ein einzelner Connector managen sollte, variiert. Das hängt von der Art der Arbeitsumgebungen, der Anzahl der Volumes, der zu verwaltenden Kapazität und der Anzahl der Benutzer ab.

Nutzen Sie eine umfangreiche Implementierung, arbeiten Sie mit Ihrem NetApp Ansprechpartner zusammen, um die Größe Ihrer Umgebung zu dimensionieren. Sollten Sie während des gesamten Chats Probleme haben, können Sie sich mit uns in Verbindung setzen.

In einigen Fällen benötigen Sie möglicherweise nur einen Connector, aber Sie benötigen möglicherweise zwei oder mehr Anschlüsse.

Hier nur ein paar Beispiele:

* Sie verfügen über eine Multi-Cloud-Umgebung (z. B. AWS und Azure) und bevorzugen einen Connector in AWS und einen weiteren in Azure. Jedes managt die Cloud Volumes ONTAP Systeme, die in diesen Umgebungen ausgeführt werden.
* Ein Service-Provider nutzt möglicherweise eine BlueXP  Organisation, um ihren Kunden Services bereitzustellen, während ein anderes Unternehmen für Disaster Recovery für einen seiner Geschäftseinheiten einsetzt. Jedes Unternehmen verfügt über separate Connectors.

