---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers 
summary: Mit NetApp BlueXP steht Ihrem Unternehmen eine einzelne Managementplattform zur Verfügung, mit der Sie Ihre Daten über Ihre On-Premises- und Cloud-Umgebungen hinweg erstellen, schützen und regeln können. Die BlueXP SaaS-Plattform umfasst Services für Storage-Management, Datenmobilität, Datensicherung sowie Datenanalyse und -Kontrolle. Managementfunktionen werden über eine webbasierte Konsole und APIs bereitgestellt. 
---
= Erfahren Sie mehr über BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit NetApp BlueXP steht Ihrem Unternehmen eine einzelne Managementplattform zur Verfügung, mit der Sie Ihre Daten über Ihre On-Premises- und Cloud-Umgebungen hinweg erstellen, schützen und regeln können. Die BlueXP SaaS-Plattform umfasst Services für Storage-Management, Datenmobilität, Datensicherung sowie Datenanalyse und -Kontrolle. Managementfunktionen werden über eine webbasierte Konsole und APIs bereitgestellt.



== Funktionen

Die BlueXP Plattform umfasst vier Hauptsäulen des Datenmanagements: Storage, Mobilität, Sicherung sowie Analyse und Kontrolle.

Storage:: Erkennen, implementieren und managen Sie Storage in AWS, Azure, Google Cloud oder vor Ort.
+
--
* Einrichtung und Verwendung https://bluexp.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] Für effizientes, Cloud-übergreifendes Multi-Protokoll-Datenmanagement
* Cloud-File-Storage-Services einrichten und verwenden:
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Dateien"^]
** https://bluexp.netapp.com/fsx-for-ontap["Amazon FSX für ONTAP"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service für Google Cloud"^]


* Erkennung und Management https://bluexp.netapp.com/netapp-on-premises["On-Premises-Storage"^]:
+
** E-Series Systeme
** ONTAP Cluster
** StorageGRID Systeme




--
Mobilität:: Daten werden durch Synchronisierung, Kopieren, Tiering und Caching von Daten dorthin verschoben, wo sie benötigt werden.
+
--
* https://bluexp.netapp.com/cloud-sync-service["Kopieren und Synchronisieren"^]
* https://bluexp.netapp.com/global-file-cache["Edge-Caching"^]
* https://bluexp.netapp.com/cloud-tiering["Tiering"^]


--
Darstellt:: Automatisierte Sicherungsmechanismen schützen Daten vor Datenverlust, ungeplanten Ausfällen, Ransomware und anderen Cyberbedrohungen.
+
--
* https://bluexp.netapp.com/cloud-backup["Backup und Recovery"^]
* https://bluexp.netapp.com/replication["Replizierung"^]
* https://bluexp.netapp.com/solutions/kubernetes["Datensicherung für Kubernetes-Workloads"^]


--
Analyse und Kontrolle:: Mit Tools können Sie Ihren Storage und Ihre Infrastruktur überwachen, zuordnen und optimieren. Nützliche Informationen für die Optimierung von Storage-Zustand, Ausfallsicherheit und Wirtschaftlichkeit
+
--
* https://bluexp.netapp.com/netapp-cloud-data-sense["Klassifizierung"^]
* https://bluexp.netapp.com/digital-advisor["Digitaler Berater"^]
* https://bluexp.netapp.com/digital-advisor["Wirtschaftliche Effizienz"^]
* https://bluexp.netapp.com/digital-advisor["Operative Ausfallsicherheit"^]


--


https://bluexp.netapp.com/["Erfahren Sie mehr darüber, wie Sie BlueXP für Ihr Unternehmen einsetzen können"^]



== Unterstützte Cloud-Provider

Mit BlueXP können Sie Cloud-Storage managen und Cloud-Services in Amazon Web Services, Microsoft Azure und Google Cloud nutzen.



== Kosten

Die Preise für BlueXP hängen von den Leistungen ab, die Sie verwenden möchten. https://bluexp.netapp.com/pricing["Weitere Informationen zu den Preisen für BlueXP"^]



== Funktionsweise von BlueXP

BlueXP umfasst eine webbasierte Konsole, die über die SaaS-Schicht bereitgestellt wird, Konten für Mandantenfähigkeit und Connectors, die Arbeitsumgebungen managen und BlueXP Cloud-Services aktivieren.



=== Software-as-a-Service

Auf BlueXP kann über eine zugegriffen werden https://console.bluexp.netapp.com["Webbasierte Konsole"^] Und APIs. Dank SaaS-Erfahrung können Sie automatisch auf die neuesten Funktionen zugreifen, sobald sie veröffentlicht wurden, und ganz einfach zwischen Ihren BlueXP Konten und Connectors wechseln.



=== BlueXP-Konto

Wenn Sie sich zum ersten Mal bei BlueXP anmelden, werden Sie aufgefordert, ein _BlueXP Konto_ zu erstellen. Dieses Konto bietet Mandantenfähigkeit und ermöglicht es Ihnen, Benutzer und Ressourcen in isolierten Arbeitsbereichen zu organisieren_.

link:concept-netapp-accounts.html["Hier erfahren Sie mehr über Accounts"].



=== Anschlüsse

Für den Einstieg in BlueXP benötigen Sie keinen Connector, aber Sie müssen einen Connector erstellen, mit dem Sie alle BlueXP Funktionen und Services nutzen können. Ein Connector ermöglicht Ihnen das Management von Ressourcen und Prozessen in Ihren On-Premises- und Cloud-Umgebungen. Sie ist erforderlich, um Arbeitsumgebungen (z. B. Cloud Volumes ONTAP und lokale ONTAP-Cluster) zu managen und viele BlueXP Datenservices zu nutzen.

link:concept-connectors.html["Erfahren Sie mehr über Steckverbinder"].



=== Eingeschränkter Modus und privater Modus

BlueXP wird auch in Umgebungen mit Einschränkungen bei Sicherheit und Konnektivität unterstützt. Sie können den _Restricted Mode_ oder _Private Mode_ verwenden, um die Outbound-Konnektivität zur BlueXP SaaS-Ebene zu beschränken.

link:concept-modes.html["Weitere Informationen zu den BlueXP Implementierungsmodi"].



== SOC 2 Typ 2-Zertifizierung

Ein unabhängiger zertifizierter Wirtschaftsprüfer und Wirtschaftsprüfer prüfte BlueXP und bestätigte, dass es SOC 2 Typ 2-Berichte basierend auf den geltenden Trust Services-Kriterien erreichte.

https://www.netapp.com/company/trust-center/compliance/soc-2/["SOC 2-Berichte von NetApp anzeigen"^]
