---
settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Installations- und Administrationsdokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/reference-limitations.html"
    - title: Änderungen an unterstützten Linux-Betriebssystemen
      url: "/reference-connector-operating-system-changes.html"
  - title: Los geht's
    entries:
    - title: Lernen Sie die Grundlagen kennen
      entries:
      - title: BlueXP
        url: "/concept-overview.html"
      - title: Konten
        url: "/concept-netapp-accounts.html"
      - title: Anschlüsse
        url: "/concept-connectors.html"
      - title: Bereitstellungsmodi
        url: "/concept-modes.html"
    - title: Beginnen Sie mit dem Standardmodus
      entries:
      - title: Erste Schritte für den Workflow
        url: "/task-quick-start-standard-mode.html"
      - title: Networking zur Nutzung der BlueXP Konsole vorbereiten
        url: "/reference-networking-saas-console.html"
      - title: Melden Sie sich bei BlueXP an
        url: "/task-sign-up-saas.html"
      - title: Einen Konnektor erstellen
        entries:
        - title: AWS
          entries:
          - title: Anschlussinstallationsoptionen
            url: "/concept-install-options-aws.html"
          - title: Erstellen Sie einen Connector von BlueXP
            url: "/task-install-connector-aws-bluexp.html"
          - title: Erstellen Sie einen Connector vom Marktplatz
            url: "/task-install-connector-aws-marketplace.html"
          - title: Installieren Sie den Connector manuell
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: Anschlussinstallationsoptionen
            url: "/concept-install-options-azure.html"
          - title: Erstellen Sie einen Connector von BlueXP
            url: "/task-install-connector-azure-bluexp.html"
          - title: Erstellen Sie einen Connector vom Marktplatz
            url: "/task-install-connector-azure-marketplace.html"
          - title: Installieren Sie den Connector manuell
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Anschlussinstallationsoptionen
            url: "/concept-install-options-google.html"
          - title: Connector von BlueXP oder gcloude erstellen
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: Installieren Sie den Connector manuell
            url: "/task-install-connector-google-manual.html"
        - title: On-Premises
          url: "/task-install-connector-on-prem.html"
      - title: Abonnieren Sie BlueXP
        url: "/task-subscribe-standard-mode.html"
      - title: Was Sie als Nächstes tun können
        url: "/reference-whats-next.html"
    - title: Beginnen Sie mit dem eingeschränkten Modus
      entries:
      - title: Erste Schritte für den Workflow
        url: "/task-quick-start-restricted-mode.html"
      - title: Vorbereitungen für die Implementierung
        url: "/task-prepare-restricted-mode.html"
      - title: Implementieren Sie den Connector
        url: "/task-install-restricted-mode.html"
      - title: Abonnieren Sie BlueXP
        url: "/task-subscribe-restricted-mode.html"
      - title: Was Sie als Nächstes tun können
        url: "/reference-whats-next-restricted-mode.html"
    - title: Starten Sie mit dem privaten Modus
      entries:
      - title: Erste Schritte für den Workflow
        url: "/task-quick-start-private-mode.html"
      - title: Vorbereitungen für die Implementierung
        url: "/task-prepare-private-mode.html"
      - title: Implementieren Sie den Connector
        url: "/task-install-private-mode.html"
      - title: Was Sie als Nächstes tun können
        url: "/reference-whats-next-private-mode.html"
    - title: Melden Sie sich bei BlueXP an
      url: "/task-logging-in.html"
  - title: Verwalten von BlueXP
    entries:
    - title: Identitätsföderation
      url: "/concept-federation.html"
    - title: BlueXP Accounts
      entries:
      - title: Managen Sie Ihr BlueXP Konto
        url: "/task-managing-netapp-accounts.html"
      - title: Überwachen Sie den Betrieb Ihres Kontos
        url: "/task-monitor-cm-operations.html"
      - title: Ein weiteres BlueXP Konto erstellen
        url: "/task-create-account.html"
      - title: Benutzerrollen
        url: "/reference-user-roles.html"
    - title: Anschlüsse
      entries:
      - title: Wartung der VM und des Betriebssystems
        url: "/task-maintain-connectors.html"
      - title: Installieren Sie ein HTTPS-Zertifikat für sicheren Zugriff
        url: "/task-installing-https-cert.html"
      - title: Konfigurieren Sie einen Konnektor für die Verwendung eines Proxy-Servers
        url: "/task-configuring-proxy.html"
      - title: Erfordern die Verwendung von IMDSv2 auf EC2-Instanzen
        url: "/task-require-imdsv2.html"
      - title: Aktualisieren Sie einen Connector, wenn Sie den privaten Modus verwenden
        url: "/task-upgrade-connector.html"
      - title: Arbeiten Sie mit mehreren Anschlüssen
        url: "/task-manage-multiple-connectors.html"
      - title: Fehlersuche für den Anschluss durchführen
        url: "/task-troubleshoot-connector.html"
      - title: Deinstallieren Sie den Connector, und entfernen Sie ihn
        url: "/task-uninstall-connector.html"
      - title: Standardkonfiguration
        url: "/reference-connector-default-config.html"
    - title: Anmeldedaten und Abonnements
      entries:
      - title: AWS
        entries:
        - title: Informationen zu Anmeldeinformationen und Berechtigungen
          url: "/concept-accounts-aws.html"
        - title: Anmeldeinformationen und Abonnements verwalten
          url: "/task-adding-aws-accounts.html"
      - title: Azure
        entries:
        - title: Informationen zu Anmeldeinformationen und Berechtigungen
          url: "/concept-accounts-azure.html"
        - title: Anmeldeinformationen und Abonnements verwalten
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: Erfahren Sie mehr über Projekte und Berechtigungen
          url: "/concept-accounts-gcp.html"
        - title: Anmeldeinformationen und Abonnements verwalten
          url: "/task-adding-gcp-accounts.html"
      - title: NSS-Anmeldedaten managen, die mit einem BlueXP Konto verknüpft sind
        url: "/task-adding-nss-accounts.html"
      - title: Managen Sie die mit Ihren BlueXP Anmeldedaten verbundenen Zugangsdaten
        url: "/task-manage-user-credentials.html"
  - title: Referenz
    entries:
    - title: Berechtigungen
      entries:
      - title: Zusammenfassung der Berechtigungen
        url: "/reference-permissions.html"
      - title: AWS-Berechtigungen für den Connector
        url: "/reference-permissions-aws.html"
      - title: Azure-Berechtigungen für den Connector
        url: "/reference-permissions-azure.html"
      - title: Google Cloud-Berechtigungen für den Connector
        url: "/reference-permissions-gcp.html"
    - title: Ports
      entries:
      - title: Regeln für die Connector-Sicherheitsgruppe in AWS
        url: "/reference-ports-aws.html"
      - title: Regeln für die Connector-Sicherheitsgruppe in Azure
        url: "/reference-ports-azure.html"
      - title: Connector-Firewall-Regeln in Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Anschlüsse für den On-Prem Connector
        url: "/reference-ports-on-prem.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
