---
settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Installations- und Administrationsdokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Einschränkungen
      url: "/reference-limitations.html"
  - title: Los geht's
    entries:
    - title: Lernen Sie die Grundlagen kennen
      entries:
      - title: BlueXP im Überblick
        url: "/concept-overview.html"
      - title: Konten
        url: "/concept-netapp-accounts.html"
      - title: Anschlüsse
        url: "/concept-connectors.html"
      - title: Bereitstellungsmodi
        url: "/concept-modes.html"
    - title: Beginnen Sie mit dem Standardmodus
      entries:
      - title: Schnellstart
        url: "/task-quick-start-standard-mode.html"
      - title: Netzwerk für Konsolenzugriff
        url: "/reference-networking-saas-console.html"
      - title: Melden Sie sich bei BlueXP an
        url: "/task-sign-up-saas.html"
      - title: Melden Sie sich bei BlueXP an
        url: "/task-logging-in.html"
      - title: Einen Konnektor erstellen
        entries:
        - title: AWS
          entries:
          - title: Schnellstart
            url: "/task-quick-start-connector-aws.html"
          - title: Installationsoptionen an
            url: "/concept-install-options-aws.html"
          - title: Netzwerk einrichten
            url: "/task-set-up-networking-aws.html"
          - title: Host-Anforderungen prüfen
            url: "/reference-host-requirements-aws.html"
          - title: AWS-Berechtigungen einrichten
            url: "/task-set-up-permissions-aws.html"
          - title: Erstellen Sie den Konnektor
            url: "/task-install-connector-aws.html"
          - title: Berechtigungen für BlueXP bereitstellen
            url: "/task-provide-permissions-aws.html"
        - title: Azure
          entries:
          - title: Schnellstart
            url: "/task-quick-start-connector-azure.html"
          - title: Installationsoptionen an
            url: "/concept-install-options-azure.html"
          - title: Netzwerk einrichten
            url: "/task-set-up-networking-azure.html"
          - title: Host-Anforderungen prüfen
            url: "/reference-host-requirements-azure.html"
          - title: Azure-Berechtigungen einrichten
            url: "/task-set-up-permissions-azure.html"
          - title: Erstellen Sie den Konnektor
            url: "/task-install-connector-azure.html"
          - title: Berechtigungen für BlueXP bereitstellen
            url: "/task-provide-permissions-azure.html"
        - title: Google Cloud
          entries:
          - title: Schnellstart
            url: "/task-quick-start-connector-google.html"
          - title: Installationsoptionen an
            url: "/concept-install-options-google.html"
          - title: Netzwerk einrichten
            url: "/task-set-up-networking-google.html"
          - title: Host-Anforderungen prüfen
            url: "/reference-host-requirements-google.html"
          - title: Google Cloud-Berechtigungen einrichten
            url: "/task-set-up-permissions-google.html"
          - title: Aktivieren Sie Google Cloud-APIs
            url: "/task-enable-apis-google.html"
          - title: Erstellen Sie den Konnektor
            url: "/task-install-connector-google.html"
          - title: Berechtigungen für BlueXP bereitstellen
            url: "/task-provide-permissions-google.html"
        - title: On-Premises
          entries:
          - title: Schnellstart
            url: "/task-quick-start-connector-on-prem.html"
          - title: Netzwerk einrichten
            url: "/task-set-up-networking-on-prem.html"
          - title: Host-Anforderungen prüfen
            url: "/reference-host-requirements-on-prem.html"
          - title: Cloud-Berechtigungen einrichten
            url: "/task-set-up-permissions-on-prem.html"
          - title: Erstellen Sie den Konnektor
            url: "/task-install-connector-on-prem.html"
          - title: Berechtigungen für BlueXP bereitstellen
            url: "/task-provide-permissions-on-prem.html"
      - title: Abonnieren Sie BlueXP
        url: "/task-subscribe-standard-mode.html"
      - title: Was Sie als Nächstes tun können
        url: "/reference-whats-next.html"
    - title: Beginnen Sie mit dem eingeschränkten Modus
      entries:
      - title: Schnellstart
        url: "/task-quick-start-restricted-mode.html"
      - title: Vorbereitungen für die Implementierung
        url: "/task-prepare-restricted-mode.html"
      - title: Implementieren Sie den Connector
        url: "/task-install-restricted-mode.html"
      - title: Melden Sie sich bei BlueXP an
        url: "/task-log-in-restricted-mode.html"
      - title: Abonnieren Sie BlueXP
        url: "/task-subscribe-restricted-mode.html"
      - title: Was Sie als Nächstes tun können
        url: "/reference-whats-next-restricted-mode.html"
    - title: Starten Sie mit dem privaten Modus
      entries:
      - title: Schnellstart
        url: "/task-quick-start-private-mode.html"
      - title: Vorbereitungen für die Implementierung
        url: "/task-prepare-private-mode.html"
      - title: Implementieren Sie den Connector
        url: "/task-install-private-mode.html"
      - title: Melden Sie sich bei BlueXP an
        url: "/task-log-in-private-mode.html"
      - title: Was Sie als Nächstes tun können
        url: "/reference-whats-next-private-mode.html"
  - title: Verwalten von BlueXP
    entries:
    - title: Identitätsföderation
      url: "/concept-federation.html"
    - title: BlueXP Accounts
      entries:
      - title: Konto verwalten
        url: "/task-managing-netapp-accounts.html"
      - title: Überwachen Sie den Betrieb Ihres Kontos
        url: "/task-monitor-cm-operations.html"
      - title: Erstellen Sie ein anderes Konto
        url: "/task-create-account.html"
      - title: Benutzerrollen
        url: "/reference-user-roles.html"
    - title: Anschlüsse
      entries:
      - title: Suchen Sie die System-ID für einen Anschluss
        url: "/task-finding-system-id.html"
      - title: Verwalten Sie vorhandene Anschlüsse
        url: "/task-managing-connectors.html"
      - title: Installieren Sie ein HTTPS-Zertifikat
        url: "/task-installing-https-cert.html"
      - title: Konfigurieren Sie Proxy-Einstellungen
        url: "/task-configuring-proxy.html"
      - title: Standardkonfiguration
        url: "/reference-connector-default-config.html"
    - title: Anmeldedaten
      entries:
      - title: AWS Zugangsdaten managen
        entries:
        - title: Überblick
          url: "/concept-accounts-aws.html"
        - title: Anmeldeinformationen und Abonnements verwalten
          url: "/task-adding-aws-accounts.html"
      - title: Azure-Anmeldedaten managen
        entries:
        - title: Überblick
          url: "/concept-accounts-azure.html"
        - title: Anmeldeinformationen und Abonnements verwalten
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud-Anmeldedaten managen
        entries:
        - title: Überblick
          url: "/concept-accounts-gcp.html"
        - title: Anmeldeinformationen und Abonnements verwalten
          url: "/task-adding-gcp-accounts.html"
      - title: NSS-Anmeldedaten managen, die mit einem BlueXP Konto verknüpft sind
        url: "/task-adding-nss-accounts.html"
      - title: Managen Sie die mit Ihren BlueXP Anmeldedaten verbundenen Zugangsdaten
        url: "/task-manage-user-credentials.html"
    - title: Cloud Storage erkannt
      entries:
      - title: Amazon S3 Buckets managen
        url: "/task-viewing-amazon-s3.html"
      - title: Azure Blob-Konten managen
        url: "/task-viewing-azure-blob.html"
      - title: Management von Google Cloud Storage Buckets
        url: "/task-viewing-gcp-storage.html"
  - title: Referenz
    entries:
    - title: Berechtigungen
      entries:
      - title: Zusammenfassung der Berechtigungen
        url: "/reference-permissions.html"
      - title: AWS-Berechtigungen für den Connector
        url: "/reference-permissions-aws.html"
      - title: Azure-Berechtigungen für den Connector
        url: "/reference-permissions-azure.html"
      - title: Google Cloud-Berechtigungen für den Connector
        url: "/reference-permissions-gcp.html"
    - title: Ports
      entries:
      - title: Sicherheitsgruppenregeln in AWS
        url: "/reference-ports-aws.html"
      - title: Für Sicherheitsgruppen gibt es in Azure Regeln
        url: "/reference-ports-azure.html"
      - title: Firewall-Regeln in Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Anschlüsse für den On-Prem Connector
        url: "/reference-ports-on-prem.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Erfahren Sie mehr über BlueXP
      url: concept-overview.html
    - title: Informieren Sie sich über Bereitstellungsmodi
      url: concept-modes.html
    - title: Beginnen Sie mit dem Standardmodus
      url: "/task-quick-start-standard-mode.html"
    - title: Beginnen Sie mit dem eingeschränkten Modus
      url: "/task-quick-start-restricted-mode.html"
    - title: Starten Sie mit dem privaten Modus
      url: "/task-quick-start-private-mode.html"
  - title: BlueXP Accounts
    links:
    - title: Mehr zu BlueXP Accounts
      url: concept-netapp-accounts.html
    - title: Managen Sie Ihr BlueXP Konto
      url: task-managing-netapp-accounts.html
    - title: Überwachen Sie den Betrieb Ihres Kontos
      url: task-monitor-cm-operations.html
  - title: Anschlüsse
    links:
    - title: Erfahren Sie mehr über Steckverbinder
      url: concept-connectors.html
    - title: Einen Connector in AWS erstellen (Standardmodus)
      url: task-quick-start-connector-aws.html
    - title: Connector in Azure erstellen (Standardmodus)
      url: task-quick-start-connector-azure.html
    - title: Connector in Google Cloud erstellen (Standardmodus)
      url: task-quick-start-connector-google.html
    - title: Erstellen eines Connectors On-Premises (Standardmodus)
      url: task-quick-start-connector-on-prem.html
    - title: Anschlüsse Verwalten
      url: task-managing-connectors.html
  - title: Berechtigungen
    links:
    - title: Zusammenfassung der Berechtigungen
      url: reference-permissions.html
    - title: AWS-Berechtigungen für den Connector
      url: reference-permissions-aws.html
    - title: Azure-Berechtigungen für den Connector
      url: reference-permissions-azure.html
    - title: Google Cloud-Berechtigungen für den Connector
      url: reference-permissions-gcp.html
  - title: Anmeldedaten
    links:
    - title: AWS Zugangsdaten managen
      url: task-adding-aws-accounts.html
    - title: Azure-Anmeldedaten managen
      url: task-adding-azure-accounts.html
    - title: Google Cloud-Anmeldedaten managen
      url: task-adding-gcp-accounts.html
    - title: Verwalten Sie die NSS-Anmeldedaten für Ihr Konto
      url: task-adding-nss-accounts.html
  - title: Blogs und Community
    links:
    - title: NetApp Community
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXP-Blog
      url: https://bluexp.netapp.com/blog
    - title: Cloud-Webinare
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: Alle BlueXP-Dokumentationen
