---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: Bei der Nutzung der webbasierten Konsole von BlueXP, die über die SaaS-Schicht bereitgestellt wird, werden mehrere Endpunkte kontaktiert, wenn einige Administrationsaufgaben durchgeführt werden. Computer, die auf die BlueXP Konsole zugreifen, sollten über Verbindungen zu diesen Endpunkten verfügen. 
---
= Networking zur Nutzung der BlueXP Konsole vorbereiten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bei der Nutzung der webbasierten Konsole von BlueXP, die über die SaaS-Schicht bereitgestellt wird, werden mehrere Endpunkte kontaktiert, wenn einige Administrationsaufgaben durchgeführt werden. Computer, die auf die BlueXP Konsole zugreifen, sollten über Verbindungen zu diesen Endpunkten verfügen.

Diese Endpunkte werden von dem Computer eines Benutzers kontaktiert, wenn bestimmte Aktionen über die BlueXP Konsole durchgeführt werden. Sie sollten auch die Netzwerkanforderungen für den Connector und bestimmte BlueXP Services beachten. Weitere Informationen finden Sie unter den entsprechenden Links am Ende dieser Seite.

[cols="2*"]
|===
| Endpunkte | Zweck 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Wenn Sie die webbasierte Konsole von BlueXP verwenden, kontaktiert Ihr Webbrowser diese URLs. 


| \https://aiq.netapp.com | Voraussetzung für den Zugang zum digitalen Berater von BlueXP. 


 a| 
AWS-Services (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Key Management Service (KMS)
* Security Token Service (STS)
* Simple Storage Service (S3)

| Für die Bereitstellung eines Connectors von BlueXP in AWS erforderlich. Der genaue Endpunkt hängt von der Region ab, in der Sie den Connector bereitstellen. https://docs.aws.amazon.com/general/latest/gr/rande.html["Weitere Informationen finden Sie in der AWS-Dokumentation."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | Für die Implementierung eines Connectors von BlueXP in den meisten Azure Regionen erforderlich. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Für die Implementierung eines Connectors von BlueXP in Azure-Regionen in Deutschland erforderlich. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Erforderlich für die Bereitstellung eines Connectors von BlueXP in Azure US Gov Regionen. 


| \https://www.googleapis.com | Erforderlich, um einen Connector von BlueXP in Google Cloud bereitzustellen. 


| \https://signin.b2c.netapp.com | Erforderlich, um die Zugangsdaten für die NetApp Support Site (NSS) zu aktualisieren oder neue NSS-Zugangsdaten für BlueXP hinzuzufügen 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Ihr Webbrowser stellt eine Verbindung zu diesen Endpunkten her, um eine zentralisierte Benutzerauthentifizierung über BlueXP zu ermöglicht. 


| \https://widget.intercom.io | Für Ihren Produkt-Chat, der Ihnen das Gespräch mit NetApp Cloud-Experten ermöglicht. 
|===
Über diese Endpunkte hinaus müssen Sie auch sicherstellen, dass der Connector über einen ausgehenden Internetzugang zu kontaktspezifischen Endpunkten für den täglichen Betrieb verfügt. Die Liste dieser Endpunkte finden Sie unter den Links im nächsten Abschnitt unten.

.Weiterführende Links
* Bereiten Sie die Vernetzung für den Connector vor
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["AWS-Netzwerk einrichten"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Azure Networking einrichten"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Google Cloud-Netzwerke einrichten"]
** link:task-install-connector-on-prem.html#step-2-set-up-networking["On-Premises-Netzwerke einrichten"]


* Networking für BlueXP Services vorbereiten
+
Informationen zu jedem BlueXP Service finden Sie in der Dokumentation.

+
https://docs.netapp.com/us-en/bluexp-family/["BlueXP-Dokumentation"^]


