---
sidebar: sidebar 
permalink: reference-ports-aws.html 
keywords: ports, security group, http, https, inbound, outbound 
summary: Für die AWS Sicherheitsgruppe für den Connector sind sowohl ein- als auch ausgehende Regeln erforderlich. BlueXP erstellt diese Sicherheitsgruppe automatisch, wenn Sie einen Connector aus BlueXP erstellen. Sie müssen diese Sicherheitsgruppe für alle anderen Installationsoptionen einrichten. 
---
= Regeln für die Connector-Sicherheitsgruppe in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Für die AWS Sicherheitsgruppe für den Connector sind sowohl ein- als auch ausgehende Regeln erforderlich. BlueXP erstellt diese Sicherheitsgruppe automatisch, wenn Sie einen Connector aus BlueXP erstellen. Sie müssen diese Sicherheitsgruppe für alle anderen Installationsoptionen einrichten.



== Regeln für eingehende Anrufe

[cols="10,10,80"]
|===
| Protokoll | Port | Zweck 


| SSH | 22 | Bietet SSH-Zugriff auf den Connector-Host 


| HTTP | 80 | Bietet HTTP-Zugriff von Client-Webbrowsern auf die lokale Benutzeroberfläche 


| HTTPS | 443 | Bietet HTTPS-Zugriff von Client-Webbrowsern auf die lokale Benutzeroberfläche und Verbindungen von der BlueXP Klassifizierungsinstanz 


| TCP | 3128 | Ermöglicht Cloud Volumes ONTAP den Zugang zum Internet, um AutoSupport-Nachrichten an den NetApp Support zu senden. Nach der Bereitstellung müssen Sie diesen Port manuell öffnen. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-verify-autosupport.html["Erfahren Sie, wie der Connector als Proxy für AutoSupport-Nachrichten verwendet wird"^] 


| TCP | 9060, 9061 | BlueXP Klassifizierung und BlueXP Backup und Recovery in Regierungsregionen lassen sich aktivieren und nutzen. 
|===


== Regeln für ausgehende Anrufe

Die vordefinierte Sicherheitsgruppe für den Konnektor öffnet den gesamten ausgehenden Datenverkehr. Wenn dies akzeptabel ist, befolgen Sie die grundlegenden Regeln für ausgehende Anrufe. Wenn Sie strengere Regeln benötigen, verwenden Sie die erweiterten Outbound-Regeln.



=== Grundlegende Regeln für ausgehende Anrufe

Die vordefinierte Sicherheitsgruppe für den Connector enthält die folgenden ausgehenden Regeln.

[cols="20,20,60"]
|===
| Protokoll | Port | Zweck 


| Alle TCP | Alle | Gesamter abgehender Datenverkehr 


| Alle UDP-Protokolle | Alle | Gesamter abgehender Datenverkehr 
|===


=== Erweiterte Outbound-Regeln

Wenn Sie starre Regeln für ausgehenden Datenverkehr benötigen, können Sie die folgenden Informationen verwenden, um nur die Ports zu öffnen, die für die ausgehende Kommunikation durch den Konnektor erforderlich sind.


NOTE: Die Quell-IP-Adresse ist der Connector-Host.

[cols="5*"]
|===
| Service | Protokoll | Port | Ziel | Zweck 


| API-Aufrufe und AutoSupport | HTTPS | 443 | Outbound-Internet und ONTAP Cluster Management LIF | API-Aufrufe an AWS, ONTAP, BlueXP Klassifizierung und das Senden von AutoSupport Nachrichten an NetApp 


.2+| API-Aufrufe | TCP | 3000 | ONTAP HA Mediator | Kommunikation mit dem ONTAP HA Mediator 


| TCP | 8080 | BlueXP Klassifizierung | Durchführung von Prüfanfragen zur BlueXP Klassifizierungsinstanz während der Implementierung 


| DNS | UDP | 53 | DNS | Wird für DNS Resolve von BlueXP verwendet 
|===