---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: Bei der Nutzung der webbasierten Konsole von BlueXP, die über die SaaS-Schicht bereitgestellt wird, werden mehrere Endpunkte kontaktiert, wenn einige Administrationsaufgaben durchgeführt werden. Computer, die auf die BlueXP Konsole zugreifen, sollten über Verbindungen zu diesen Endpunkten verfügen. 
---
= Bereiten Sie das Netzwerk für die BlueXP -Konsole vor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie sich anmelden und die webbasierte Konsole verwenden, kontaktiert BlueXP mehrere Endpunkte, um die von Ihnen initiierten Aktionen auszuführen. Computer, die auf die Konsole zugreifen, müssen Verbindungen zu diesen Endpunkten haben.

Diese Endpunkte werden in zwei Szenarien kontaktiert:

* Vom Computer eines Benutzers beim Ausfüllen von Abschnitten aus dem https://console.bluexp.netapp.com["BlueXP webbasierte Konsole"^] die als Software as a Service (SaaS) verfügbar ist.
* Vom Computer eines Benutzers beim Öffnen eines Webbrowsers, Eingabe der IP-Adresse des Connectors und anschließende Anmeldung und Einrichtung des Connectors. Diese Schritte sind erforderlich, wenn Sie den Connector manuell installieren.


[cols="2*"]
|===
| Endpunkte | Zweck 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Dies ist der Endpunkt, den Sie in Ihren Webbrowser eingeben, um die webbasierte Konsole zu verwenden. 


| \https://api.bluexp.netapp.com | Die webbasierte Konsole kontaktiert diesen Endpunkt, um mit der API für Aktionen im Zusammenhang mit Autorisierung, Lizenzierung, Abonnements, Anmeldeinformationen, Benachrichtigungen und mehr zu interagieren. 


| \https://aiq.netapp.com | Erforderlich für den Zugriff auf den digitalen Berater. 


 a| 
AWS-Services (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Key Management Service (KMS)
* Security Token Service (STS)
* Simple Storage Service (S3)

| Für die Bereitstellung eines Connectors von BlueXP in AWS erforderlich. Der genaue Endpunkt hängt von der Region ab, in der Sie den Connector bereitstellen.  https://docs.aws.amazon.com/general/latest/gr/rande.html["Weitere Einzelheiten finden Sie in der AWS-Dokumentation."] Anregung:  https://docs.aws.amazon.com/general/latest/gr/rande.html["Weitere Einzelheiten finden Sie in der AWS-Dokumentation."] 


| \https://management.azure.com

\https://login.microsoftonline.com | Für die Implementierung eines Connectors von BlueXP in den meisten Azure Regionen erforderlich. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Für die Implementierung eines Connectors von BlueXP in Azure-Regionen in Deutschland erforderlich. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Erforderlich für die Bereitstellung eines Connectors von BlueXP in Azure US Gov Regionen. 


| \https://www.googleapis.com | Erforderlich, um einen Connector von BlueXP in Google Cloud bereitzustellen. 


| \https://signin.b2c.netapp.com | Erforderlich, um die Zugangsdaten für die NetApp Support Site (NSS) zu aktualisieren oder neue NSS-Zugangsdaten für BlueXP hinzuzufügen 


| \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://cdn.auth0.com \https://services.cloud.netapp.com | Ihr Webbrowser stellt eine Verbindung zu diesen Endpunkten her, um eine zentralisierte Benutzerauthentifizierung über BlueXP zu ermöglicht. 


| \https://widget.intercom.io | Für den In-Product-Chat, der es Ihnen ermöglicht, mit dem NetApp-Support zu sprechen. 
|===
Stellen Sie sicher, dass der Connector ausgehenden Internetzugriff auf die Kontaktendpunkte für den täglichen Betrieb hat. Folgen Sie den Links im nächsten Abschnitt, um die Liste dieser Endpunkte anzuzeigen.

.Verwandte Informationen
* Bereiten Sie die Vernetzung für den Connector vor
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["AWS-Netzwerk einrichten"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Azure Networking einrichten"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Google Cloud-Netzwerke einrichten"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["Einrichten des lokalen Netzwerks"]


* Networking für BlueXP Services vorbereiten
+
Informationen zu jedem BlueXP Service finden Sie in der Dokumentation.

+
https://docs.netapp.com/us-en/bluexp-family/["BlueXP-Dokumentation"^]


