---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: Bei der Nutzung der webbasierten Konsole von BlueXP, die über die SaaS-Schicht bereitgestellt wird, werden mehrere Endpunkte kontaktiert, wenn einige Administrationsaufgaben durchgeführt werden. Computer, die auf die BlueXP Konsole zugreifen, sollten über Verbindungen zu diesen Endpunkten verfügen. 
---
= Bereiten Sie das Netzwerk für die BlueXP -Konsole vor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie sich anmelden und die webbasierte BlueXP -Konsole verwenden, kontaktiert BlueXP  mehrere Endpunkte, um die von Ihnen initiierten Aktionen durchzuführen. Computer, die auf die BlueXP -Konsole zugreifen, müssen über Verbindungen zu diesen Endpunkten verfügen.

Diese Endpunkte werden in zwei Szenarien kontaktiert:

* Vom Computer eines Benutzers, wenn bestimmte Aktionen vom ausgeführt https://console.bluexp.netapp.com["BlueXP webbasierte Konsole"^] werden, die als Software-as-a-Service (SaaS) verfügbar sind.
* Vom Computer eines Benutzers beim Öffnen eines Webbrowsers, Eingabe der IP-Adresse des Connectors und anschließende Anmeldung und Einrichtung des Connectors. Diese Schritte sind erforderlich, wenn Sie den Connector manuell installieren.


[cols="2*"]
|===
| Endpunkte | Zweck 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Dies ist der Endpunkt, den Sie im Webbrowser zur Verwendung der webbasierten Konsole von BlueXP  eingeben. 


| \https://api.bluexp.netapp.com | Die webbasierte BlueXP -Konsole kontaktiert diesen Endpunkt, um mit der BlueXP -API für Aktionen in Bezug auf Autorisierung, Lizenzierung, Abonnements, Anmeldeinformationen, Benachrichtigungen und vieles mehr zu interagieren. 


| \https://aiq.netapp.com | Voraussetzung für den Zugang zum digitalen Berater von BlueXP. 


 a| 
AWS-Services (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Key Management Service (KMS)
* Security Token Service (STS)
* Simple Storage Service (S3)

| Für die Bereitstellung eines Connectors von BlueXP in AWS erforderlich. Der genaue Endpunkt hängt von der Region ab, in der Sie den Connector bereitstellen. https://docs.aws.amazon.com/general/latest/gr/rande.html["Weitere Informationen finden Sie in der AWS-Dokumentation."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | Für die Implementierung eines Connectors von BlueXP in den meisten Azure Regionen erforderlich. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Für die Implementierung eines Connectors von BlueXP in Azure-Regionen in Deutschland erforderlich. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Erforderlich für die Bereitstellung eines Connectors von BlueXP in Azure US Gov Regionen. 


| \https://www.googleapis.com | Erforderlich, um einen Connector von BlueXP in Google Cloud bereitzustellen. 


| \https://signin.b2c.netapp.com | Erforderlich, um die Zugangsdaten für die NetApp Support Site (NSS) zu aktualisieren oder neue NSS-Zugangsdaten für BlueXP hinzuzufügen 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Ihr Webbrowser stellt eine Verbindung zu diesen Endpunkten her, um eine zentralisierte Benutzerauthentifizierung über BlueXP zu ermöglicht. 


| \https://widget.intercom.io | Für Ihren Produkt-Chat, der Ihnen das Gespräch mit NetApp Cloud-Experten ermöglicht. 
|===
Über diese Endpunkte hinaus müssen Sie auch sicherstellen, dass der Connector über einen ausgehenden Internetzugang zu kontaktspezifischen Endpunkten für den täglichen Betrieb verfügt. Die Liste dieser Endpunkte finden Sie unter den Links im nächsten Abschnitt unten.

.Verwandte Informationen
* Bereiten Sie die Vernetzung für den Connector vor
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["AWS-Netzwerk einrichten"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Azure Networking einrichten"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Google Cloud-Netzwerke einrichten"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["Einrichten des lokalen Netzwerks"]


* Networking für BlueXP Services vorbereiten
+
Informationen zu jedem BlueXP Service finden Sie in der Dokumentation.

+
https://docs.netapp.com/us-en/bluexp-family/["BlueXP-Dokumentation"^]


