---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: Stellen Sie bei den ersten Schritten mit BlueXP sicher, dass Ihr Netzwerk über die BlueXP Konsole Zugriff auf bestimmte Endpunkte ermöglicht. Je nachdem, wie Sie BlueXP planten, müssen Sie möglicherweise auch Networking für einen Connector und für bestimmte BlueXP Services einrichten. 
---
= Bereiten Sie Ihr Netzwerk vor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Stellen Sie bei den ersten Schritten mit BlueXP sicher, dass Ihr Netzwerk über die BlueXP Konsole Zugriff auf bestimmte Endpunkte ermöglicht. Je nachdem, wie Sie BlueXP planten, müssen Sie möglicherweise auch Networking für einen Connector und für bestimmte BlueXP Services einrichten.



== Bereiten Sie Ihr Networking auf den Benutzerzugriff auf die BlueXP Konsole vor

Bei der Nutzung der webbasierten Konsole von BlueXP, die über die SaaS-Schicht bereitgestellt wird, werden mehrere Endpunkte kontaktiert, um Datenmanagement-Aufgaben durchzuführen. Der Computer, auf dem der Webbrowser ausgeführt wird, muss über Verbindungen zu diesen Endpunkten verfügen.

[cols="2*"]
|===
| Endpunkte | Zweck 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Wenn Sie die webbasierte Konsole von BlueXP verwenden, kontaktiert Ihr Webbrowser diese URLs. 


 a| 
AWS-Services (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Key Management Service (KMS)
* Security Token Service (STS)
* Simple Storage Service (S3)

| Für die Bereitstellung eines Connectors von BlueXP in AWS erforderlich. Der genaue Endpunkt hängt von der Region ab, in der Sie den Connector bereitstellen. https://docs.aws.amazon.com/general/latest/gr/rande.html["Weitere Informationen finden Sie in der AWS-Dokumentation."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | Für die Implementierung eines Connectors von BlueXP in den meisten Azure Regionen erforderlich. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Für die Implementierung eines Connectors von BlueXP in Azure-Regionen in Deutschland erforderlich. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Erforderlich für die Bereitstellung eines Connectors von BlueXP in Azure US Gov Regionen. 


| \https://www.googleapis.com | Erforderlich, um einen Connector von BlueXP in Google Cloud bereitzustellen. 


| \https://signin.b2c.netapp.com | Erforderlich, um die Zugangsdaten für die NetApp Support Site (NSS) zu aktualisieren oder neue NSS-Zugangsdaten für BlueXP hinzuzufügen 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Ihr Webbrowser stellt eine Verbindung zu diesen Endpunkten her, um eine zentralisierte Benutzerauthentifizierung über BlueXP zu ermöglicht. 


| \https://widget.intercom.io | Für Ihren Produkt-Chat, der Ihnen das Gespräch mit NetApp Cloud-Experten ermöglicht. 
|===
Über diese Endpunkte hinaus müssen Sie auch sicherstellen, dass der Connector über einen ausgehenden Internetzugang zu kontaktspezifischen Endpunkten für den täglichen Betrieb verfügt. Die Liste dieser Endpunkte finden Sie unter den Links im nächsten Abschnitt unten.



== Bereiten Sie die Vernetzung für einen Connector vor

Wie Sie Ihr Netzwerk auf einen Connector vorbereiten, hängt davon ab, wo Sie den Connector installieren möchten, der sich in der Cloud oder vor Ort befinden kann. Weitere Informationen zu den Netzwerkanforderungen des Connectors finden Sie auf den folgenden Seiten:

* link:task-set-up-networking-aws.html["AWS-Netzwerk einrichten"]
* link:task-set-up-networking-azure.html["Azure Networking einrichten"]
* link:task-set-up-networking-google.html["Google Cloud-Netzwerke einrichten"]
* link:task-set-up-networking-on-prem.html["On-Premises-Netzwerke einrichten"]




== Networking für BlueXP Services vorbereiten

Bei den ersten Schritten mit BlueXP sollten Sie sicherstellen, dass die Netzwerkanforderungen für die von Ihnen geplanten BlueXP Services erfüllt sind. Weitere Informationen finden Sie in der Dokumentation zu den einzelnen Services.

https://docs.netapp.com/us-en/bluexp-family/["BlueXP-Dokumentation"^]
