---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: Das Identitäts- und Zugriffsmanagement von BlueXP  umfasst mehrere vordefinierte Rollen, die Sie den Mitgliedern Ihres Unternehmens zuweisen können. 
---
= Vordefinierte BlueXP  IAM-Rollen und -Berechtigungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das Identitäts- und Zugriffsmanagement (BlueXP  Identity and Access Management, IAM) umfasst mehrere vordefinierte Rollen, die Sie den Mitgliedern Ihres Unternehmens über verschiedene Ebenen Ihrer Ressourcenhierarchie zuweisen können. Bevor Sie diese Rollen zuweisen, sollten Sie die Berechtigungen verstehen, die jede Rolle beinhaltet.



== Organisationsadministrator

Beschreibung:: Bietet volle Kontrolle über die gesamte BlueXP -Organisation.
Berechtigungen:: Ein Mitglied mit dieser Rolle kann alle Aktionen in BlueXP  ausführen.




== Ordner- oder Projektadministrator

Beschreibung:: Bietet volle Kontrolle über ein oder mehrere Projekte und Ordner.
+
--
Wenn Sie diese Rolle auf Ordnerebene zuweisen, hat das Mitglied Berechtigungen für alle Projekte, die diesem Ordner zugeordnet sind.

--
Berechtigungen:: Ein Mitglied mit dieser Rolle kann die folgenden Aktionen in BlueXP  ausführen:
+
--
* Verwalten Sie alle Arbeitsumgebungen in den Projekten und Ordnern, für die sie Berechtigungen haben
* Alle BlueXP -Dienste verwenden
* Über BlueXP  IAM kann ein Administrator eines Ordners die Ordner, Projekte und Ressourcen verwalten, die untergeordnete Elemente dieses Ordners sind:
+
** Ordner oder Projekte innerhalb des Ordners hinzufügen
** Ordner und Projekte bearbeiten: Namen, zugeordnete Ressourcen und Mitgliederzugriff
** Ordner und Projekte löschen
** Fügen Sie ein Benutzerkonto hinzu und verknüpfen Sie eine Rolle auf Ordner- oder Projektebene
** Verknüpfen eines Connectors mit einem Ordner oder Projekt
** Fügen Sie einem Mitglied auf Ordner- oder Projektebene eine Rolle hinzu
** Zeigen Sie Ressourcen an, die mit Ordnern und Projekten verknüpft sind
** Zuordnen ansichtbarer Ressourcen zu zusätzlichen Ordnern oder Projekten
** Trennen Sie eine Ressource von einem Ordner oder Projekt


* Über BlueXP  IAM kann ein Administrator eines Projekts dieses Projekt und seine zugehörigen Ressourcen wie folgt verwalten:
+
** Bearbeiten Sie das Projekt: Seinen Namen, die zugehörigen Ressourcen und den Zugriff auf Mitglieder
** Fügen Sie ein Benutzerkonto hinzu und verknüpfen Sie eine Rolle auf Projektebene
** Verknüpfen Sie einen Connector mit einem Projekt, wenn das Mitglied Administratorrechte für andere Projekte hat, denen andere Connectors zugeordnet sind
** Fügen Sie einem Mitglied auf Projektebene eine Rolle hinzu
** Mit dem Projekt verknüpfte Ressourcen anzeigen
** Ressourcen mit dem Projekt verknüpfen, wenn das Mitglied über Administratorberechtigungen für andere Projekte verfügt, denen andere Ressourcen zugeordnet sind
** Distanzieren Sie eine Ressource vom Projekt
** Löschen Sie das Projekt


* Verwalten Sie Anmeldeinformationen über Einstellungen > Anmeldeinformationen
* Sehen Sie sich den BlueXP -Zeitplan an
* Registrieren Sie BlueXP , um Support zu erhalten, und senden Sie Cases ein


--




== SnapCenter-Admin

Beschreibung:: Bietet die Möglichkeit, Snapshots aus lokalen ONTAP Clustern mithilfe von BlueXP  Backup und Recovery für Applikationen zu sichern.
Berechtigungen:: Ein Mitglied mit dieser Rolle kann die folgenden Aktionen in BlueXP  ausführen:
+
--
* Führen Sie alle Aktionen über Backup und Recovery > Anwendungen aus
* Verwalten Sie alle Arbeitsumgebungen in den Projekten und Ordnern, für die sie Berechtigungen haben
* Alle BlueXP -Dienste verwenden


--




== Klassifizierungs-Viewer

Beschreibung:: Bietet die Möglichkeit, die Ergebnisse der BlueXP -Klassifikation anzuzeigen.
Berechtigungen:: Zeigen Sie Compliance-Informationen an und erstellen Sie Berichte für Ressourcen, auf die sie zugreifen dürfen. Diese Benutzer können das Scannen von Volumes, Buckets oder Datenbankschemas nicht aktivieren oder deaktivieren.
+
--
Einem Mitglied, das diese Rolle hat, stehen keine anderen Aktionen zur Verfügung.

--




== Weiterführende Links

* link:concept-identity-and-access-management.html["Erfahren Sie mehr über das Identitäts- und Zugriffsmanagement von BlueXP "]
* link:task-iam-get-started.html["Erste Schritte mit BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["Verwalten von BlueXP -Mitgliedern und deren Berechtigungen"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["Erfahren Sie mehr über die API für BlueXP  IAM"^]

