---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: Das Identitäts- und Zugriffsmanagement von BlueXP  umfasst mehrere vordefinierte Rollen, die Sie den Mitgliedern Ihres Unternehmens zuweisen können. 
---
= Vordefinierte BlueXP  IAM-Rollen und -Berechtigungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das Identitäts- und Zugriffsmanagement (BlueXP  Identity and Access Management, IAM) umfasst mehrere vordefinierte Rollen, die Sie den Mitgliedern Ihres Unternehmens über verschiedene Ebenen Ihrer Ressourcenhierarchie zuweisen können. Bevor Sie diese Rollen zuweisen, sollten Sie die Berechtigungen verstehen, die jede Rolle beinhaltet. Die Rollen lassen sich in drei Kategorien einteilen: Plattform, Applikation und Datenservice.



== Plattformrollen

Plattformrollen sind die breitesten Rollen, die Sie Benutzern zuweisen können und die umfassende Berechtigungen für die BlueXP -Administration ermöglichen, einschließlich der Zuweisung von Rollen und Hinzufügen von Benutzern sowie der Möglichkeit, alle BlueXP -Funktionen auszuführen. BlueXP  IAM umfasst zwei Plattformrollen: Organisationsadministrator und Ordner oder Projektadministrator. Der Hauptunterschied zwischen den beiden BlueXP  IAM-Plattformrollen ist der Umfang.



=== Organisationsadministrator

Ermöglicht einem Benutzer uneingeschränkten Zugriff auf alle Projekte und Ordner innerhalb einer Organisation, Hinzufügen von Mitgliedern zu einem beliebigen Projekt oder Ordner sowie Durchführung jeder BlueXP -Aufgabe und Nutzung aller Datendienste.



=== Ordner- oder Projektadministrator

Ermöglicht einem Benutzer uneingeschränkten Zugriff auf bestimmte Projekte und Ordner, denen er zugewiesen ist. Sie können Mitglieder zu Projekten oder Ordnern hinzufügen, die sie verwalten, sowie beliebige BlueXP -Aufgaben ausführen und jeden Datendienst innerhalb des Ordners oder Projekts nutzen, dem sie zugewiesen sind.

Die Rolle „Ordner“ oder „Projektadministrator“ kann keine Konnektoren erstellen.



=== Vergleichstabelle für Plattformrollen

[cols="24,19,19"]
|===
| Aufgabe | Organisationsadministrator | Ordner- oder Projektadministrator 


| Erstellen Sie Konnektoren | Ja. | Nein 


| Erstellen, Ändern oder Löschen von Arbeitsumgebungen (Hinzufügen oder Erkennen neuer Ressourcen über den BlueXP -Bildschirm) | Ja. | Ja. 


| Erstellen Sie Projekte/Ordner, einschließlich Löschen | Ja. | Nein 


| Umbenennen vorhandener Projekte/Ordner | Ja. | Ja. 


| Rollen zuweisen und Benutzer hinzufügen | Ja. | Ja. 


| Ressourcen mit Ordnern und Projekten verknüpfen | Ja. | Ja. 


| Verknüpfen von Konnektoren mit Ordnern und Projekten | Ja. | Nein 


| Entfernen von Konnektoren aus Ordnern und Projekten | Ja. | Nein 


| Connectors verwalten (Zertifikate, Einstellungen usw. bearbeiten) | Ja. | Nein 


| Verwalten Sie Anmeldeinformationen über Einstellungen > Anmeldeinformationen | Ja. | Ja. 


| Sehen Sie sich den BlueXP -Zeitplan an | Ja. | Ja. 


| Nutzung von BlueXP  Services | Ja. | Ja. 


| Registrieren Sie BlueXP , um Support zu erhalten, und senden Sie Cases ein | Ja. | Ja. 
|===
Beispiel für Organisationsrollen in BlueXP  für eine große multinationale Organisation:: XYZ Corporation, ein multinationales Unternehmen, zielt darauf ab, den Zugriff auf Datenspeicherressourcen nach geografischen Regionen wie Nordamerika, Europa und Asien-Pazifik zu trennen. Sie möchten, dass jede Region exklusive Kontrolle über ihre Ressourcen hat und gleichzeitig eine zentrale Übersicht erhält.
+
--
Um dies zu erreichen, erstellt eine Person, die der Rolle „Organisationsadministrator“ im BlueXP  der XYZ Corporation zugewiesen ist, eine anfängliche Arbeitsumgebung und erstellt dann für jede Region separate Ordner in BlueXP . Der Ordner jeder Region enthält Projekte (mit zugehörigen Ressourcen), die mit dieser Region zusammenhängen. Der Organisationsadministrator weist einem BlueXP -Benutzer in jeder Region die Rolle „Ordner/Projekt-Administrator“ zu.

Sobald die Ersteinrichtung abgeschlossen ist, können regionale Administratoren mit der Rolle „Ordner“ oder „Projektadministrator“ neue Arbeitsumgebungen erstellen und Benutzer in ihren Regionen hinzufügen. Diese regionalen Administratoren können auch Ordner und Projekte hinzufügen, entfernen oder umbenennen, denen sie zugewiesen sind. Der Unternehmensadministrator erbt Berechtigungen für neue Arbeitsumgebungen oder Ressourcen und sorgt so für Transparenz der Storage-Auslastung im gesamten Unternehmen.

--




== Anwendungsrollen

Anwendungsrollen ermöglichen den Zugriff auf BlueXP -Anwendungen wie Active IQ Digital Advisor (auch als digitaler Berater bekannt).



=== Storage-Admin

Benutzer können in BlueXP  Storage-Administrationsfunktionen wie Software-Updates und das Erstellen und Löschen von BlueXP  Arbeitsumgebungen ausführen.

Berechtigungen:: Kann den BlueXP -Bildschirm anzeigen. Kann BlueXP -Konnektoren erstellen und verwalten. Lese-/Schreibzugriff auf Storage-Zustands- und Governance-Funktionen von BlueXP , darunter:
+
--
* Digitaler Berater
* Operative Ausfallsicherheit
* Software-Updates (können Software-Updates durchführen)
* Digitale Brieftasche
* Wirtschaftliche Effizienz
* Dashboard zur Nachhaltigkeit
* Meldungen


--




=== Storage-Prüfer

Bietet schreibgeschützten Zugriff auf Systemzustands- und Governance-Funktionen von BlueXP . Diese Rolle wird normalerweise Benutzern zugewiesen, die für die Überwachung des Zustands der Speicherressourcen eines Unternehmens verantwortlich sind. Benutzer mit dieser Rolle können mehrere Applikationen in BlueXP  anzeigen, um Software-Update-Pläne und Effizienzpläne zu erstellen und den Storage-Zustand insgesamt anzuzeigen.

Berechtigungen:: Schreibgeschützter Zugriff auf Storage-Zustands- und Governance-Funktionen von BlueXP , darunter:
+
--
* Digitaler Berater
* Operative Ausfallsicherheit
* Software-Updates (kann Upgrade-Pläne herunterladen)
* Digitale Brieftasche
* Wirtschaftliche Effizienz
* Dashboard zur Nachhaltigkeit
* Meldungen


--




== Datenservices

Data Services-Rollen bieten Benutzern die Berechtigung zur Verwendung von Datenservices innerhalb der Organisation, des Projekts oder des Ordners, auf die sie zugreifen können.



=== SnapCenter-Admin

Bietet die Möglichkeit, Snapshots aus lokalen ONTAP Clustern mithilfe von BlueXP  Backup und Recovery für Applikationen zu sichern.

Berechtigungen:: Ein Mitglied mit dieser Rolle kann die folgenden Aktionen in BlueXP  ausführen:
+
--
* Führen Sie alle Aktionen über Backup und Recovery > Anwendungen aus
* Verwalten Sie alle Arbeitsumgebungen in den Projekten und Ordnern, für die sie Berechtigungen haben
* Alle BlueXP -Dienste verwenden


--




=== Klassifizierungs-Viewer

Bietet die Möglichkeit, die Ergebnisse der BlueXP -Klassifikation anzuzeigen.

Berechtigungen:: Zeigen Sie Compliance-Informationen an und erstellen Sie Berichte für Ressourcen, auf die sie zugreifen dürfen. Diese Benutzer können das Scannen von Volumes, Buckets oder Datenbankschemas nicht aktivieren oder deaktivieren.
+
--
Einem Mitglied, das diese Rolle hat, stehen keine anderen Aktionen zur Verfügung.

--




== Weiterführende Links

* link:concept-identity-and-access-management.html["Erfahren Sie mehr über das Identitäts- und Zugriffsmanagement von BlueXP "]
* link:task-iam-get-started.html["Erste Schritte mit BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["Verwalten von BlueXP -Mitgliedern und deren Berechtigungen"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["Erfahren Sie mehr über die API für BlueXP  IAM"^]

