---
sidebar: sidebar 
permalink: reference-host-requirements-on-prem.html 
keywords: cpu requirements, ram requirements, on prem requirements, on prem host requirements, connector host requirements 
summary: Die Connector-Software muss auf einem Host ausgeführt werden, der bestimmte Betriebssystemanforderungen, RAM-Anforderungen, Port-Anforderungen usw. erfüllt. Stellen Sie sicher, dass Ihr Host diese Anforderungen erfüllt, bevor Sie den Connector installieren. 
---
= Prüfen Sie die Connector-Host-Anforderungen für On-Premises-Installationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Connector-Software muss auf einem Host ausgeführt werden, der bestimmte Betriebssystemanforderungen, RAM-Anforderungen, Port-Anforderungen usw. erfüllt. Stellen Sie sicher, dass Ihr Host diese Anforderungen erfüllt, bevor Sie den Connector installieren.

Dedizierter Host:: Der Connector wird nicht auf einem Host unterstützt, der für andere Anwendungen freigegeben ist. Der Host muss ein dedizierter Host sein.
Unterstützte Betriebssysteme::
+
--
* Ubuntu 22.04
* CentOS 7.6, 7.7, 7.8 und 7.9
* Red hat Enterprise Linux 7.6, 7.7, 7.8 und 7.9
+
Der Host muss bei Red hat Subscription Management registriert sein. Wenn er nicht registriert ist, kann der Host während der Connector-Installation nicht auf Repositorys zugreifen, um erforderliche Drittanbietersoftware zu aktualisieren.

+
Der Connector wird auf Englisch-sprachigen Versionen dieser Betriebssysteme unterstützt.



--
Hypervisor:: Ein Bare-Metal- oder Hosted-Hypervisor, der für Ubuntu, CentOS oder Red hat Enterprise Linux zertifiziert ist, ist erforderlich.
+
--
https://["Red hat Solution: Welche Hypervisoren sind für die Ausführung von Red hat Enterprise Linux zertifiziert?"^]

--
CPU:: 4 Kerne oder 4 vCPUs
RAM:: 14 GB
Speicherplatz in /opt:: 100 gib Speicherplatz muss verfügbar sein
Festplattenspeicher in /var:: 20 gib Speicherplatz muss verfügbar sein
Docker Engine:: Docker Engine Version 19.3.1 oder höher ist auf dem Host erforderlich, bevor Sie den Connector installieren. https://["Installationsanweisungen anzeigen"^]

