---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: Das Identitäts- und Zugriffsmanagement von BlueXP  umfasst mehrere vordefinierte Rollen, die Sie den Mitgliedern Ihres Unternehmens zuweisen können. 
---
= Zugriffsrollen für BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das Identitäts- und Zugriffsmanagement (BlueXP  Identity and Access Management, IAM) umfasst mehrere vordefinierte Rollen, die Sie den Mitgliedern Ihres Unternehmens über verschiedene Ebenen Ihrer Ressourcenhierarchie zuweisen können. Bevor Sie diese Rollen zuweisen, sollten Sie die Berechtigungen verstehen, die jede Rolle beinhaltet. Die Rollen lassen sich in folgende Kategorien einteilen: Plattform, Applikation und Datenservice.



== Plattformrollen

Plattformrollen sind die breitesten Rollen, die Sie Benutzern zuweisen können. Sie erlauben alle Berechtigungen für die BlueXP Administration, einschließlich dem Zuweisen von Rollen und dem Hinzufügen von Benutzern. Benutzer mit Plattformrollen haben Zugriff auf alle Datenservices und Applikationen innerhalb von BlueXP . BlueXP  IAM umfasst zwei Plattformrollen: Organisationsadministrator und Ordner oder Projektadministrator. Der Hauptunterschied zwischen den beiden BlueXP  IAM-Plattformrollen ist der Umfang.



=== Organisationsadministrator

Ermöglicht einem Benutzer uneingeschränkten Zugriff auf alle Projekte und Ordner innerhalb einer Organisation, Hinzufügen von Mitgliedern zu einem beliebigen Projekt oder Ordner sowie Durchführung jeder BlueXP -Aufgabe und Nutzung aller Datendienste.



=== Ordner- oder Projektadministrator

Ermöglicht einem Benutzer uneingeschränkten Zugriff auf bestimmte Projekte und Ordner, denen er zugewiesen ist. Sie können Mitglieder zu Ordnern oder Projekten hinzufügen, die sie verwalten, sowie beliebige BlueXP -Aufgaben ausführen und beliebige Datendienste oder Anwendungen auf Ressourcen innerhalb des Ordners oder Projekts verwenden, denen sie zugewiesen sind.

Die Rolle „Ordner“ oder „Projektadministrator“ kann keine Connectors erstellen.



=== Vergleichstabelle für Plattformrollen

[cols="24,19,19"]
|===
| Aufgabe | Organisationsadministrator | Ordner- oder Projektadministrator 


| Anschlüsse Erstellen | Ja. | Nein 


| Erstellen, Ändern oder Löschen von Arbeitsumgebungen (Hinzufügen oder Erkennen neuer Ressourcen über den BlueXP -Bildschirm) | Ja. | Ja. 


| Erstellen Sie Ordner und Projekte, einschließlich Löschen | Ja. | Nein 


| Umbenennen vorhandener Ordner und Projekte | Ja. | Ja. 


| Rollen zuweisen und Benutzer hinzufügen | Ja. | Ja. 


| Ressourcen mit Ordnern und Projekten verknüpfen | Ja. | Ja. 


| Connectors mit Ordnern und Projekten verknüpfen | Ja. | Nein 


| Entfernen Sie Connectors aus Ordnern und Projekten | Ja. | Nein 


| Connectors verwalten (Zertifikate, Einstellungen usw. bearbeiten) | Ja. | Nein 


| Verwalten Sie Anmeldeinformationen über Einstellungen > Anmeldeinformationen | Ja. | Ja. 


| Sehen Sie sich den BlueXP -Zeitplan an | Ja. | Ja. 


| Nutzung von BlueXP  Services | Ja. | Ja. 


| Registrieren Sie BlueXP , um Support zu erhalten, und senden Sie Cases ein | Ja. | Ja. 
|===
Beispiel für Organisationsrollen in BlueXP  für eine große multinationale Organisation:: XYZ Corporation, ein multinationales Unternehmen, zielt darauf ab, den Zugriff auf Datenspeicherressourcen nach geografischen Regionen wie Nordamerika, Europa und Asien-Pazifik zu trennen. Sie möchten, dass jede Region exklusive Kontrolle über ihre Ressourcen hat und gleichzeitig eine zentrale Übersicht erhält.
+
--
Um dies zu erreichen, erstellt eine Person, die der Rolle „Organisationsadministrator“ im BlueXP  der XYZ Corporation zugewiesen ist, eine anfängliche Arbeitsumgebung und erstellt dann für jede Region separate Ordner in BlueXP . Der Ordner jeder Region enthält Projekte (mit zugehörigen Ressourcen), die mit dieser Region zusammenhängen. Der Administrator der Organisation weist einem BlueXP -Benutzer in jeder Region die Rolle „Ordner/Projekt-Administrator“ zu.

Sobald die Ersteinrichtung abgeschlossen ist, können regionale Administratoren mit der Rolle „Ordner“ oder „Projektadministrator“ neue Arbeitsumgebungen erstellen und Benutzer in ihren Regionen hinzufügen. Diese regionalen Administratoren können auch Ordner und Projekte hinzufügen, entfernen oder umbenennen, denen sie zugewiesen sind. Der Unternehmensadministrator erbt Berechtigungen für neue Arbeitsumgebungen oder Ressourcen und sorgt so für Transparenz der Storage-Auslastung im gesamten Unternehmen.

--




== Anwendungsrollen

Im Folgenden finden Sie eine Liste der Rollen in der Anwendungskategorie. Jede Rolle gewährt bestimmte Berechtigungen innerhalb ihres festgelegten Umfangs. Benutzer, die nicht über die erforderliche Anwendungsrolle oder eine Plattformrolle verfügen, können nicht auf die Anwendung zugreifen.



=== Keystone Rollen

Mithilfe der folgenden Rollen können Sie Benutzern Zugriff auf Keystone zuweisen.


NOTE: Der Zugriff auf Keystone über BlueXP  ist derzeit in der Beta-Phase. Wenn Sie an der Keystone Beta-Version teilnehmen möchten, wenden Sie sich an Ihren NetApp Ansprechpartner.

* *Keystone admin*: Verwalten Sie das Keystone Abonnement und ergreifen Sie Maßnahmen zu Warnungen, Berichten und Abonnements.
* *Keystone Viewer*: Sehen Sie sich das Keystone Abonnement an und sehen Sie sich Berichte, Warnungen und Assets an.


Die folgende Tabelle zeigt die Aktionen, die die einzelnen Keystone Rollen durchführen können.

[cols="40,20a,20a"]
|===
| Funktion und Aktion | Keystone Admin | Keystone Viewer 


| Zeigen Sie die folgenden Registerkarten an: Abonnement, Assets, Monitor und Administration  a| 
Ja.
 a| 
Ja.



3+| *Keystone Abonnementseite*: 


| Abonnements anzeigen  a| 
Ja.
 a| 
Ja.



| Abonnements ändern oder erneuern  a| 
Ja.
 a| 
Nein



3+| *Seite „Keystone Assets“*: 


| Assets anzeigen  a| 
Ja.
 a| 
Ja.



| Verwalten von Assets  a| 
Ja.
 a| 
Nein



3+| *Keystone-Alerts-Seite*: 


| Anzeigen von Meldungen  a| 
Ja.
 a| 
Nein



| Verwalten von Meldungen  a| 
Ja.
 a| 
Nein



| Erstellen Sie Warnmeldungen für sich selbst.  a| 
Ja.
 a| 
Ja.



3+| *Digital Wallet*: 


| Digital Wallet anzeigen können  a| 
Ja.
 a| 
Ja.



3+| *Keystone-Berichtsseite*: 


| Berichte herunterladen  a| 
Ja.
 a| 
Ja.



| Verwalten von Berichten  a| 
Ja.
 a| 
Ja.



| Erstellen Sie Berichte für sich selbst.  a| 
Ja.
 a| 
Ja.



3+| *Serviceanfragen*: 


| Erstellen Sie Serviceanfragen  a| 
Ja.
 a| 
Nein



| CView-Serviceanforderungen, die von einem beliebigen Benutzer innerhalb der Organisation erstellt wurden  a| 
Ja.
 a| 
Ja.

|===


== Datenservice-Rollen

Nachfolgend finden Sie eine Liste der Rollen in der Datenservicekategorie. Jede Rolle gewährt bestimmte Berechtigungen innerhalb ihres festgelegten Umfangs. Benutzer, die nicht über die erforderliche Rolle für den Datenservice oder eine Plattformfunktion verfügen, können nicht auf den Datenservice zugreifen.



=== Klassifizierungs-Viewer

Bietet die Möglichkeit, die Ergebnisse der BlueXP -Klassifikation anzuzeigen.

Die Klassifizierung hat keine Administratorrolle.

Berechtigungen:: Zeigen Sie Compliance-Informationen an und erstellen Sie Berichte für Ressourcen, auf die sie zugreifen dürfen. Diese Benutzer können das Scannen von Volumes, Buckets oder Datenbankschemas nicht aktivieren oder deaktivieren.


Einem Mitglied, das diese Rolle hat, stehen keine anderen Aktionen zur Verfügung.



=== Schutz durch Ransomware

Mit den folgenden Rollen können Sie Benutzern Zugriff auf einen Ransomware-Schutz zuweisen.

* *Ransomware-Schutz admin*: Verwalten Sie Aktionen auf den Registerkarten Schützen, Warnungen, Wiederherstellen, Einstellungen und Berichte.
* *Ransomware Protection Viewer*: Workload-Daten anzeigen, Warnungsdaten anzeigen, Wiederherstellungsdaten herunterladen und Berichte herunterladen.


Die folgende Tabelle zeigt, dass Aktionen ausgeführt werden können, die jede BlueXP  Ransomware-Schutzrolle ausführen kann.

[cols="40,20a,20a"]
|===
| Funktion und Aktion | Administrator für Ransomware-Schutz | Viewer für Ransomware-Schutz 


| Dashboard und alle Registerkarten anzeigen  a| 
Ja.
 a| 
Ja.



| Kostenlos testen  a| 
Ja.
 a| 
Nein



| Beginnen Sie mit der Erkennung von Workloads  a| 
Ja.
 a| 
Nein



3+| *Auf der Registerkarte Schutz*: 


| Richtlinien hinzufügen, ändern oder löschen  a| 
Ja.
 a| 
Nein



| Schutz von Workloads  a| 
Ja.
 a| 
Nein



| Sensible Daten erkennen  a| 
Ja.
 a| 
Nein



| Bearbeiten Sie den Workload-Schutz  a| 
Ja.
 a| 
Nein



| Workload-Details anzeigen  a| 
Ja.
 a| 
Ja.



| Download von Daten  a| 
Ja.
 a| 
Ja.



3+| *Auf der Registerkarte Warnungen*: 


| Anzeigen von Alarmdetails  a| 
Ja.
 a| 
Ja.



| Bearbeiten Sie den Ereignisstatus  a| 
Ja.
 a| 
Nein



| Anzeigen von Vorfalldetails  a| 
Ja.
 a| 
Ja.



| Vollständige Liste der betroffenen Dateien abrufen  a| 
Ja.
 a| 
Nein



| Warnmeldungen herunterladen  a| 
Ja.
 a| 
Ja.



3+| *Auf der Registerkarte Wiederherstellen*: 


| Betroffene Dateien herunterladen  a| 
Ja.
 a| 
Nein



| Restore-Workload  a| 
Ja.
 a| 
Nein



| Wiederherstellungsdaten herunterladen  a| 
Ja.
 a| 
Ja.



| Berichte herunterladen  a| 
Ja.
 a| 
Ja.



3+| *Auf der Registerkarte Einstellungen*: 


| Backup-Ziele hinzufügen oder ändern  a| 
Ja.
 a| 
Nein



| SIEM-Ziele hinzufügen oder ändern  a| 
Ja.
 a| 
Nein



3+| *Auf der Registerkarte Berichte*: 


| Berichte herunterladen  a| 
Ja.
 a| 
Ja.

|===


=== SnapCenter-Admin

Bietet die Möglichkeit, Snapshots aus lokalen ONTAP Clustern mithilfe von BlueXP  Backup und Recovery für Applikationen zu sichern.

SnapCenter hat keine Viewer-Rolle.

Berechtigungen:: Ein Mitglied mit dieser Rolle kann die folgenden Aktionen in BlueXP  ausführen:
+
--
* Führen Sie alle Aktionen über Backup und Recovery > Anwendungen aus
* Verwalten Sie alle Arbeitsumgebungen in den Projekten und Ordnern, für die sie Berechtigungen haben
* Alle BlueXP -Dienste verwenden


--




== Weiterführende Links

* link:concept-identity-and-access-management.html["Erfahren Sie mehr über das Identitäts- und Zugriffsmanagement von BlueXP "]
* link:task-iam-get-started.html["Erste Schritte mit BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["Verwalten von BlueXP -Mitgliedern und deren Berechtigungen"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["Erfahren Sie mehr über die API für BlueXP  IAM"^]

