---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: Weisen Sie Benutzern Plattformrollen zu, um ihnen Berechtigungen zum Verwalten von BlueXP, zum Zuweisen von Rollen, zum Hinzufügen von Benutzern, zum Erstellen von Konnektoren und zum Verwalten von Föderationen zu erteilen. 
---
= Zugriffsrollen für die BlueXP -Plattform
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Weisen Sie Benutzern Plattformrollen zu, um ihnen Berechtigungen zum Verwalten von BlueXP, zum Zuweisen von Rollen, zum Hinzufügen von Benutzern, zum Erstellen von Konnektoren und zum Verwalten von Föderationen zu erteilen.

.Beispiel für Organisationsrollen in BlueXP  für eine große multinationale Organisation
Die XYZ Corporation organisiert den Datenspeicherzugriff nach Regionen (Nordamerika, Europa und Asien-Pazifik) und gibt jeder Region die Kontrolle, während gleichzeitig eine zentrale Übersicht gewährleistet wird.

Der *Organisationsadministrator* in BlueXP der XYZ Corporation erstellt eine anfängliche Organisation und separate Ordner für jede Region. Der Ordner jeder Region enthält Projekte (mit zugehörigen Ressourcen), die mit dieser Region zusammenhängen. Der *Organisationsadministrator* weist einem BlueXP -Benutzer in jeder Region die Rolle *Ordner oder Projektadministrator* zu.

Regionale Administratoren mit der Rolle „Ordner- oder Projektadministrator“ verwalten ihre Regionen (Ordner), indem sie neue Ressourcen und Benutzer hinzufügen. Sie können außerdem die von ihnen verwalteten Ordner und Projekte hinzufügen, entfernen oder umbenennen. Der Organisationsadministrator erhält die Berechtigungen für alle neuen Ressourcen und behält so den Überblick über die Speichernutzung in der gesamten Organisation.

Innerhalb derselben Organisation wird einem Benutzer die Rolle *Federationsadministrator* zugewiesen, um die Föderation der Organisation mit seinem Unternehmens-IdP zu verwalten. Dieser Benutzer kann föderierte Organisationen hinzufügen oder entfernen, jedoch keine Benutzer oder Ressourcen innerhalb der Organisation verwalten. Die Organisation weist einem Benutzer die Rolle *Federationsbetrachter* zu, um den Föderationsstatus zu überprüfen und föderierte Organisationen anzuzeigen, ohne Änderungen vorzunehmen.

Die folgenden Tabellen zeigen die Aktionen, die jede BlueXP Plattformrolle ausführen kann.



== Rollen in der Organisationsverwaltung

[cols="2,1,1"]
|===
| Aufgabe | Organisationsadministrator | Ordner- oder Projektadministrator 


| Anschlüsse Erstellen | Ja. | Nein 


| Erstellen, Ändern oder Löschen von Arbeitsumgebungen (Hinzufügen oder Erkennen neuer Ressourcen über den BlueXP -Bildschirm) | Ja. | Ja. 


| Erstellen Sie Ordner und Projekte, einschließlich Löschen | Ja. | Nein 


| Umbenennen vorhandener Ordner und Projekte | Ja. | Ja. 


| Rollen zuweisen und Benutzer hinzufügen | Ja. | Ja. 


| Ressourcen mit Ordnern und Projekten verknüpfen | Ja. | Ja. 


| Connectors mit Ordnern und Projekten verknüpfen | Ja. | Nein 


| Entfernen Sie Connectors aus Ordnern und Projekten | Ja. | Nein 


| Connectors verwalten (Zertifikate, Einstellungen usw. bearbeiten) | Ja. | Nein 


| Verwalten Sie Anmeldeinformationen über Einstellungen > Anmeldeinformationen | Ja. | Ja. 


| Erstellen, Verwalten und Anzeigen von Föderationen | Ja. | Nein 


| Für Support registrieren und Fälle einreichen | Ja. | Ja. 


| Datendienste nutzen | Ja. | Ja. 


| Sehen Sie sich die BlueXP Zeitleiste und -Benachrichtigungen an | Ja. | Ja. 
|===


== Föderationsrollen

[cols="2,1,1"]
|===
| Aufgabe | Föderationsadministrator | Föderationsbetrachter 


| Erstellen einer Föderation | Ja. | Nein 


| Verifizieren einer Domäne | Ja. | Nein 


| Hinzufügen einer Domäne zu einem Verbund | Ja. | Nein 


| Deaktivieren und Löschen von Föderationen | Ja. | Nein 


| Testverbände | Ja. | Nein 


| Verbände und ihre Details anzeigen | Ja. | Ja. 
|===