---
sidebar: sidebar 
permalink: reference-ports-gcp.html 
keywords: ports, firewall rules, http, https, inbound, outbound 
summary: Die Google Cloud Firewall-Regeln für den Connector erfordern sowohl ein- als auch ausgehende Regeln. BlueXP erstellt diese Sicherheitsgruppe automatisch, wenn Sie einen Connector aus BlueXP erstellen. Sie müssen diese Sicherheitsgruppe für alle anderen Installationsoptionen einrichten. 
---
= Connector-Firewall-Regeln in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Google Cloud Firewall-Regeln für den Connector erfordern sowohl ein- als auch ausgehende Regeln. BlueXP erstellt diese Sicherheitsgruppe automatisch, wenn Sie einen Connector aus BlueXP erstellen. Sie müssen diese Sicherheitsgruppe für alle anderen Installationsoptionen einrichten.



== Regeln für eingehende Anrufe

[cols="10,10,80"]
|===
| Protokoll | Port | Zweck 


| SSH | 22 | Bietet SSH-Zugriff auf den Connector-Host 


| HTTP | 80  a| 
* Bietet HTTP-Zugriff von Client-Webbrowsern auf die lokale Benutzeroberfläche
* Wird während des Cloud Volumes ONTAP-Upgrade-Prozesses verwendet




| HTTPS | 443 | Bietet HTTPS-Zugriff von Client-Webbrowsern auf die lokale Benutzeroberfläche 


| TCP | 3128 | Bietet Cloud Volumes ONTAP Internetzugang. Nach der Bereitstellung müssen Sie diesen Port manuell öffnen. 
|===


== Regeln für ausgehende Anrufe

Die vordefinierten Firewall-Regeln für den Connector öffnen den gesamten ausgehenden Datenverkehr. Wenn dies akzeptabel ist, befolgen Sie die grundlegenden Regeln für ausgehende Anrufe. Wenn Sie strengere Regeln benötigen, verwenden Sie die erweiterten Outbound-Regeln.



=== Grundlegende Regeln für ausgehende Anrufe

Die vordefinierten Firewall-Regeln für den Connector enthalten die folgenden ausgehenden Regeln.

[cols="20,20,60"]
|===
| Protokoll | Port | Zweck 


| Alle TCP | Alle | Gesamter abgehender Datenverkehr 


| Alle UDP-Protokolle | Alle | Gesamter abgehender Datenverkehr 
|===


=== Erweiterte Outbound-Regeln

Wenn Sie starre Regeln für ausgehenden Datenverkehr benötigen, können Sie die folgenden Informationen verwenden, um nur die Ports zu öffnen, die für die ausgehende Kommunikation durch den Konnektor erforderlich sind.


NOTE: Die Quell-IP-Adresse ist der Connector-Host.

[cols="5*"]
|===
| Service | Protokoll | Port | Ziel | Zweck 


| API-Aufrufe und AutoSupport | HTTPS | 443 | Outbound-Internet und ONTAP Cluster Management LIF | API-Aufrufe an Google Cloud, an ONTAP, an BlueXP Klassifizierung und Senden von AutoSupport Nachrichten an NetApp 


| API-Aufrufe | TCP | 8080 | BlueXP Klassifizierung | Durchführung von Prüfanfragen zur BlueXP Klassifizierungsinstanz während der Implementierung 


| DNS | UDP | 53 | DNS | Wird für DNS Resolve von BlueXP verwendet 
|===