---
sidebar: sidebar 
permalink: reference-user-roles.html 
keywords: user, users, roles, role, task, permission, permissions, tasks, admin, Account Admin, Workspace Admin, Cloud Compliance Viewer, Cloud Data Sense, SnapCenter Admin 
summary: Die Rollen Kontoverwaltung, Arbeitsbereichsverwaltung, Compliance Viewer und SnapCenter-Admin bieten Benutzern spezifische Berechtigungen. Sie können eine dieser Rollen zuweisen, wenn Sie einen neuen Benutzer mit Ihrem BlueXP Konto verknüpfen. 
---
= Benutzerrollen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie BlueXP  im eingeschränkten oder privaten Modus verwenden, verwenden Sie ein _BlueXP -Konto_, um Benutzer zu verwalten. Sie können Benutzern in Ihrem Konto bestimmte Berechtigungen zuweisen, indem Sie eine der folgenden Rollen auswählen: Kontoadministrator, Arbeitsbereichsadministrator, Compliance-Viewer und SnapCenter-Administrator

Wenn Sie BlueXP  im Standardmodus verwenden, verfügen Sie nicht über ein BlueXP -Konto. Stattdessen verfügen Sie über eine _BlueXP -Organisation_, die Sie mit BlueXP -Identitäts- und Zugriffsmanagement (IAM) verwalten.

* link:concept-identity-and-access-management.html["Erfahren Sie mehr über BlueXP  IAM"]
* link:concept-modes.html["Weitere Informationen zu BlueXP Implementierungsmodi"]


[cols="24,19,19,19,19"]
|===
| Aufgabe | Kontoadministrator | Workspace-Verwaltung | Compliance Viewer | SnapCenter Admin 


| Anschlüsse Erstellen | Ja. | Nein | Nein | Nein 


| Verwalten von Arbeitsumgebungen | Ja. | Ja. | Nein | Ja. 


| Services in Arbeitsumgebungen ermöglichen | Ja. | Ja. | Nein | Ja. 


| Nutzung von BlueXP  Services | Ja. | Ja. | Nein | Ja. 


| Entfernen von Arbeitsumgebungen aus einem Arbeitsbereich | Ja. | Ja. | Nein | Nein 


| Arbeitsumgebungen löschen | Ja. | Ja. | Nein | Nein 


| Anzeigen des Status der Datenreplizierung | Ja. | Ja. | Nein | Nein 


| Zeitachse anzeigen | Ja. | Ja. | Nein | Nein 


| Wechseln Sie zwischen Arbeitsbereichen | Ja. | Ja. | Ja. | Ja. 


| Sehen Sie sich die Ergebnisse des BlueXP Klassifizierungs-Scans an | Ja. | Ja. | Ja. | Nein 


| Cloud Volumes ONTAP Bericht erhalten | Ja. | Nein | Nein | Nein 


| BlueXP Konten managen | Ja. | Nein | Nein | Nein 


| Anmeldeinformationen verwalten | Ja. | Ja. | Nein | Nein 


| Ändern Sie die Einstellungen von BlueXP | Ja. | Ja. | Nein | Nein 


| Anzeigen und Verwalten des Support-Dashboards | Ja. | Ja. | Nein | Nein 
|===
.Verwandte Informationen
link:task-managing-netapp-accounts.html["Managen Sie Ihr BlueXP Konto"]
