---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: Abhängig von den in BlueXP durchgeführten Aktionen verfügen Sie möglicherweise über entsprechende ONTAP Zugangsdaten und NSS-Zugangsdaten für die NetApp Support-Website mit Ihren BlueXP Benutzeranmeldung. Sie können diese Anmeldedaten in BlueXP anzeigen und managen, nachdem Sie sie verknüpft haben. Wenn Sie beispielsweise das Passwort für diese Anmeldedaten ändern, müssen Sie das Passwort in BlueXP aktualisieren. 
---
= Managen Sie die mit Ihren BlueXP Anmeldedaten verbundenen Zugangsdaten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Je nach den Aktionen, die Sie in BlueXP durchgeführt haben, können Sie Ihren BlueXP Benutzeranmeldeinformationen zur ONTAP und zur NetApp Support Website (NSS) zugeordnet haben. Sie können diese Anmeldedaten in BlueXP anzeigen und managen, nachdem Sie sie verknüpft haben. Wenn Sie beispielsweise das Passwort für diese Anmeldedaten ändern, müssen Sie das Passwort in BlueXP aktualisieren.



== ONTAP Referenzen

Benutzer benötigen ONTAP-Administratoranmeldeinformationen, um ONTAP-Cluster in BlueXP zu erkennen. Der Zugriff auf ONTAP System Manager hängt jedoch davon ab, ob Sie einen Connector verwenden.

.Ohne Steckverbinder
Die Benutzer werden aufgefordert, ihre ONTAP-Anmeldedaten einzugeben, um auf den ONTAP System Manager für das Cluster zuzugreifen. Benutzer können diese Anmeldeinformationen in BlueXP  speichern, was bedeutet, dass sie nicht jedes Mal aufgefordert werden, sie einzugeben. Benutzeranmeldeinformationen sind nur für den jeweiligen Benutzer sichtbar und können über die Seite Benutzeranmeldeinformationen verwaltet werden.

.Mit einem Connector
Standardmäßig werden Benutzer nicht aufgefordert, ihre ONTAP-Anmeldedaten für den Zugriff auf ONTAP System Manager einzugeben. Ein BlueXP -Administrator (mit der Administratorrolle des Unternehmens) kann BlueXP  jedoch so konfigurieren, dass Benutzer aufgefordert werden, ihre ONTAP-Anmeldedaten einzugeben. Wenn diese Einstellung aktiviert ist, müssen Benutzer jedes Mal ihre ONTAP-Anmeldeinformationen eingeben.

link:task-ontap-access-connector.html["Weitere Informationen ."^]



== NSS-Anmeldeinformationen

Die NSS-Zugangsdaten für Ihre BlueXP Anmeldung ermöglichen die Support-Registrierung, das Fallmanagement und den Zugriff auf Digital Advisor.

* Wenn Sie *Support > Ressourcen* aufrufen und sich für den Support registrieren, werden Sie aufgefordert, Ihre NSS-Anmeldedaten mit Ihrem BlueXP Login zu verknüpfen.
+
Dadurch wird Ihre Organisation bzw. Ihr Konto für den Support registriert und der Supportanspruch aktiviert. Nur ein Benutzer in Ihrer BlueXP  Organisation oder Ihrem Account muss ein NetApp Support Site Konto mit seinem BlueXP  Login verknüpfen, um sich für Support zu registrieren und die Support-Berechtigung zu aktivieren. Nachdem dies abgeschlossen ist, zeigt die Seite *Ressourcen* an, dass Ihr Konto für Support registriert ist.

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["Erfahren Sie, wie Sie sich für Support registrieren"^]

* Wenn Sie auf *Support > Case Management* zugreifen, werden Sie aufgefordert, Ihre NSS-Anmeldedaten einzugeben, sofern Sie dies noch nicht getan haben. Auf dieser Seite können Sie die Support-Fälle erstellen und verwalten, die mit Ihrem NSS-Konto und Ihrem Unternehmen verknüpft sind.
* Wenn Sie in BlueXP auf Digital Advisor zugreifen, werden Sie aufgefordert, sich bei Digital Advisor anzumelden, indem Sie Ihre NSS-Anmeldedaten eingeben.


Beachten Sie Folgendes zu dem NSS-Konto bei Ihrer BlueXP Anmeldung:

* Das Konto wird auf Benutzerebene verwaltet, was bedeutet, dass es von anderen Benutzern, die sich anmelden, nicht angezeigt wird.
* Digital Advisor und Support-Case-Management können nur ein NSS-Konto pro Benutzer zugeordnet werden.
* Wenn Sie versuchen, ein NetApp-Support-Site-Konto mit einer Cloud Volumes ONTAP-Arbeitsumgebung zu verknüpfen, können Sie nur aus den NSS-Konten auswählen, die der BlueXP -Organisation oder dem Konto hinzugefügt wurden, in dem Sie Mitglied sind.
+
Die Zugangsdaten für NSS Konten unterscheiden sich von dem NSS-Konto, das mit Ihrer BlueXP Anmeldung verknüpft ist. Mit den Anmeldeinformationen auf NSS-Kontoebene können Sie Cloud Volumes ONTAP mit BYOL bereitstellen, PAYGO-Systeme registrieren und die Software aktualisieren.

+
link:task-adding-nss-accounts.html["Erfahren Sie mehr über die Verwendung von NSS-Anmeldeinformationen mit Ihrer-Organisation oder Ihrem BlueXP -Konto"].





== Verwalten Sie Ihre Benutzeranmeldeinformationen

Verwalten Sie Ihre Benutzeranmeldeinformationen, indem Sie den Benutzernamen und das Kennwort aktualisieren oder die Anmeldeinformationen löschen.

.Schritte
. Klicken Sie oben rechts auf der BlueXP Konsole auf das Symbol Einstellungen, und wählen Sie *Credentials* aus.
. Wählen Sie *Benutzeranmeldeinformationen*.
. Wenn Sie noch keine Anmeldedaten für den Benutzer haben, können Sie *Add NSS Credentials* auswählen, um Ihr NetApp Support Site Konto hinzuzufügen.
. Verwalten Sie vorhandene Anmeldeinformationen, indem Sie im Menü „Aktionen“ die folgenden Optionen auswählen:
+
** *Zugangsdaten aktualisieren*: Aktualisieren Sie den Benutzernamen und das Passwort für das Konto.
** *Zugangsdaten löschen*: Entfernen Sie das Konto, das Ihrem BlueXP Benutzerkonto zugeordnet ist.




.Ergebnis
BlueXP aktualisiert Ihre Anmeldeinformationen und Sie sehen die Änderungen, wenn Sie auf den ONTAP-Cluster, den digitalen Berater oder die Fallmanagement-Seite zugreifen.
