---
sidebar: sidebar 
permalink: task-log-in-restricted-mode.html 
keywords: logging in, log in, sign in, signing in, restricted mode, restricted mode log in, local log in, connector log in, log in connector 
summary: Wenn Sie BlueXP im eingeschränkten Modus nutzen, müssen Sie sich über die lokale Benutzeroberfläche des Connector bei der BlueXP Konsole anmelden. 
---
= Bei BlueXP anmelden (eingeschränkter Modus)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie BlueXP im eingeschränkten Modus nutzen, müssen Sie sich über die lokale Benutzeroberfläche des Connector bei der BlueXP Konsole anmelden.

.Anmelde-Optionen
BlueXP unterstützt die Anmeldung über eine der folgenden Optionen, wenn Ihr Konto im eingeschränkten Modus eingerichtet wird:

* Nutzen Sie Ihre E-Mail-Adresse und ein Passwort, um sich bei einem NetApp Cloud-Login anzumelden
* Eine Verbundverbindung
+
Sie können sich mit Single Sign-On über Anmeldedaten aus Ihrem Unternehmensverzeichnis (föderierte Identität) anmelden. link:concept-federation.html["Erfahren Sie mehr über den Einsatz von Identitätsföderation mit BlueXP"].



.Schritte
. Öffnen Sie einen Webbrowser, und geben Sie die folgende URL ein:
+
https://[]

+
_Ipaddress_ kann localhost, eine private IP-Adresse oder eine öffentliche IP-Adresse sein, abhängig von der Konfiguration des Hosts, auf dem Sie den Connector installiert haben. Sie müssen beispielsweise eine private IP-Adresse von einem Host eingeben, der eine Verbindung zum Connector-Host hat.

. Geben Sie Ihren Benutzernamen und Ihr Kennwort ein, um sich anzumelden.


.Ergebnis
Sie sind jetzt angemeldet und können mit BlueXP Ihre Hybrid-Multi-Cloud-Infrastruktur managen.
