---
sidebar: sidebar 
permalink: task-log-in-private-mode.html 
keywords: logging in, log in, sign in, signing in, private mode, private mode log in, local log in, connector log in, log in connector 
summary: Wenn Sie BlueXP im privaten Modus nutzen, müssen Sie sich über die lokale Benutzeroberfläche des Connector bei der BlueXP Konsole anmelden. 
---
= Bei BlueXP anmelden (privater Modus)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie BlueXP im privaten Modus nutzen, müssen Sie sich über die lokale Benutzeroberfläche des Connector bei der BlueXP Konsole anmelden.

.Anmelde-Optionen
Der private Modus unterstützt lokale Benutzerverwaltung und -Zugriff. Authentifizierung wird nicht über den Cloud-Service von BlueXP bereitgestellt.

.Schritte
. Öffnen Sie einen Webbrowser, und geben Sie die folgende URL ein:
+
https://_ipaddress_[]

+
_Ipaddress_ kann localhost, eine private IP-Adresse oder eine öffentliche IP-Adresse sein, abhängig von der Konfiguration des Hosts, auf dem Sie den Connector installiert haben. Sie müssen beispielsweise eine private IP-Adresse von einem Host eingeben, der eine Verbindung zum Connector-Host hat.

. Geben Sie Ihren Benutzernamen und Ihr Kennwort ein, um sich anzumelden.


.Ergebnis
Sie sind jetzt angemeldet und können mit BlueXP Ihre Hybrid-Multi-Cloud-Infrastruktur managen.
