---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: Nachdem Sie sich bei BlueXP angemeldet haben, können Sie sich über die SaaS-basierte Benutzeroberfläche von Ihrem Webbrowser aus anmelden. 
---
= Melden Sie sich bei BlueXP an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem Sie sich bei BlueXP angemeldet haben, können Sie sich über die SaaS-basierte Benutzeroberfläche von Ihrem Webbrowser aus anmelden.

link:task-sign-up-saas.html["Hier erfahren Sie, wie Sie sich bei BlueXP anmelden und eine Organisation erstellen können"].

Wenn Sie über eine Regierungsregion oder eine Website ohne Outbound-Internetzugang auf BlueXP zugreifen, müssen Sie sich bei der BlueXP-Benutzeroberfläche anmelden, die lokal auf dem Connector ausgeführt wird. link:task-managing-connectors.html#access-the-local-ui["Erfahren Sie, wie Sie auf die lokale Benutzeroberfläche des Connectors zugreifen können"].

.Anmelde-Optionen
Sie können sich unter BlueXP mit einer der folgenden Optionen anmelden:

* Ihre vorhandenen Zugangsdaten für die NetApp Support Site (NSS
* Nutzen Sie Ihre E-Mail-Adresse und ein Passwort, um sich bei einem NetApp Cloud-Login anzumelden
* Eine Verbundverbindung
+
Sie können sich mit Single Sign-On über Anmeldedaten aus Ihrem Unternehmensverzeichnis (föderierte Identität) anmelden. link:concept-federation.html["Erfahren Sie mehr über den Einsatz von Identitätsföderation mit BlueXP"].



.Schritte
. Öffnen Sie einen Webbrowser, und rufen Sie den auf https://console.bluexp.netapp.com["BlueXP-Konsole"^]
. Geben Sie auf der Seite *Anmelden* die E-Mail-Adresse ein, die mit Ihrem Login verknüpft ist.
. Abhängig von der Authentifizierungsmethode, die mit Ihrer Anmeldung verknüpft ist, werden Sie aufgefordert, Ihre Anmeldedaten einzugeben:
+
** NetApp Cloud-Anmeldedaten: Geben Sie Ihr Passwort ein
** Föderierte Benutzer: Geben Sie Ihre föderierten Identitätsinformationen ein
** NetApp Support Site Konto: Geben Sie Ihre Zugangsdaten für die NetApp Support Site ein




.Ergebnis
Sie sind jetzt angemeldet und können mit BlueXP Ihre Hybrid-Multi-Cloud-Infrastruktur managen.
