---
sidebar: sidebar 
permalink: task-upgrade-connector.html 
keywords: upgrade, manual upgrade, connector upgrade, manual connector upgrade, upgrade connector manually, private mode upgrade, offline upgrade, upgrade private mode 
summary: BlueXP aktualisiert einen Connector automatisch auf die neueste Version, wenn Sie BlueXP im Standardmodus oder im eingeschränkten Modus verwenden. In der Regel werden jeden Monat neue Versionen veröffentlicht, um neue Funktionen einzuführen und die Stabilität zu verbessern. Sie können den Connector so konfigurieren, dass er statt dessen Bildaktualisierungen aus einem lokalen Repository zieht. Bei privaten Bereitstellungen müssen Sie den Connector immer manuell aktualisieren. 
---
= Management von Connector-Upgrades
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie den Standardmodus oder den eingeschränkten Modus verwenden, aktualisiert BlueXP Ihren Connector automatisch auf die neueste Version, sofern der Connector über ausgehenden Internetzugang verfügt, um das Softwareupdate abzurufen. Wenn Sie die Verwaltung bei Aktualisierung des Connectors manuell vornehmen müssen, können Sie automatische Upgrades für den Standardmodus oder den eingeschränkten Modus deaktivieren.


NOTE: Wenn Sie BlueXP  im privaten Modus ausführen, müssen Sie den Connector immer selbst aktualisieren.



== Deaktivieren Sie automatische Upgrades

Das Deaktivieren der automatischen Aktualisierung für den Connector besteht aus zwei Schritten. Zunächst müssen Sie sicherstellen, dass Ihr Connector gesund und aktuell ist. Anschließend bearbeiten Sie eine Konfigurationsdatei, um die automatische Aktualisierungsfunktion zu deaktivieren.


NOTE: Sie können die automatischen Upgrades nur deaktivieren, wenn Sie über Connector-Version 3.9.48 oder höher verfügen.



=== Überprüfen Sie den Zustand des Connectors

Sie sollten überprüfen, ob Ihr Connector stabil ist und alle Container, die auf Ihrer Konnektor-VM ausgeführt werden, ordnungsgemäß ausgeführt werden. Nachdem Sie die automatischen Upgrades deaktiviert haben, prüft die Connector-VM nicht mehr nach neuen Services oder Upgrade-Paketen.

Verwenden Sie einen der folgenden Befehle, um den Anschluss zu überprüfen. Alle Dienste sollten den Status _Running_ haben. Ist dies nicht der Fall, wenden Sie sich vor dem Deaktivieren der automatischen Aktualisierung an den NetApp Support.

Docker::
+
--
[source, cli]
----
docker ps -a
----
--
Podman::
+
--
[source, cli]
----
podman ps -a
----
--




=== Deaktivieren Sie die automatische Aktualisierung für den Connector

Sie deaktivieren die automatischen Upgrades, indem Sie in der Datei _com/opt/Application/NetApp/Service-Manager-2/config.json_ das Flag _isUpgradeDisabled_ setzen. Standardmäßig ist dieses Flag auf false gesetzt und Ihr Connector wird automatisch aktualisiert. Sie können dieses Flag auf true setzen, um automatische Upgrades zu deaktivieren. Sie sollten mit der JSON-Syntax vertraut sein, bevor Sie diesen Schritt abschließen.

Um die automatische Aktualisierung wieder zu aktivieren, verwenden Sie diese Schritte und setzen Sie das _isUpgradeDisabled_-Flag auf false.

.Schritte
. Stellen Sie sicher, dass Ihr Anschluss auf dem neuesten Stand und in gutem Zustand ist.
. Erstellen Sie eine Sicherungskopie der Datei _/opt/Application/NetApp/Service-Manager-2/config.json_, um sicherzustellen, dass Sie Ihre Änderungen rückgängig machen können.
. Bearbeiten Sie die Datei _/opt/Application/NetApp/Service-Manager-2/config.json_ und ändern Sie den Wert des Flags _isUpgradeDisabled_ auf true.
+
[source]
----
  "isUpgradeDisabled": true,
----
. Speichern Sie Ihre Datei.
. Starten Sie den Service Manager 2 neu, indem Sie den folgenden Befehl ausführen:
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. Führen Sie den folgenden Befehl aus, und überprüfen Sie, ob der Connector-Status als _Active(Running)_: _ Angezeigt wird
+
[source, cli]
----
systemctl status netapp-service-manager.service
----




== Aktualisieren Sie den Anschluss

Der Connector muss während des Upgrade-Vorgangs neu gestartet werden, damit die webbasierte Konsole während des Upgrades nicht verfügbar ist.

.Schritte
. Laden Sie die Connector-Software von der herunter https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp Support Website"^].
+
Stellen Sie sicher, dass Sie das Offline-Installationsprogramm für private Netzwerke ohne Internetzugang herunterladen.

. Kopieren Sie das Installationsprogramm auf den Linux-Host.
. Weisen Sie Berechtigungen zum Ausführen des Skripts zu.
+
[source, cli]
----
chmod +x /path/BlueXP-Connector-Offline-<version>
----
+
Wobei <version> die Version des Connectors ist, den Sie heruntergeladen haben.

. Führen Sie das Installationsskript aus:
+
[source, cli]
----
sudo /path/BlueXP-Connector-Offline-<version>
----
+
Wobei <version> die Version des Connectors ist, den Sie heruntergeladen haben.

. Nachdem die Aktualisierung abgeschlossen ist, können Sie die Version des Connectors überprüfen, indem Sie *Hilfe > Support > Connector* aufrufen.

