---
sidebar: sidebar 
permalink: task-set-up-permissions-google.html 
keywords: set up permissions, set up gcp permissions, set up google cloud permissions, google permissions, gcp permissions, service account, create service account, gcp service account, google service account 
summary: Richten Sie Google Cloud-Berechtigungen ein, damit Sie BlueXP für das Management Ihrer Daten- und Storage-Infrastruktur in Google Cloud verwenden können. 
---
= Google Cloud-Berechtigungen einrichten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Richten Sie Berechtigungen in Google Cloud ein, sodass Sie den Connector mit den Berechtigungen implementieren können, die er für das Management Ihrer Daten- und Storage-Infrastruktur benötigt.

Sie müssen Google Cloud-Berechtigungen wie folgt einrichten:

* Wenn Sie planen, den Connector aus BlueXP oder mithilfe von gCloud zu erstellen, müssen Sie Berechtigungen für den Google Cloud-Benutzer einrichten, der die Connector-VM bereitstellen wird.
* Richten Sie Berechtigungen für den Connector ein, indem Sie eine Rolle erstellen und die Rolle einem Dienstkonto zuweisen.
+
Sie verknüpfen dieses Servicekonto mit der Connector-VM, sodass BlueXP über die erforderlichen Berechtigungen verfügt.



Je nach Konfiguration müssen Sie möglicherweise auch die folgenden Schritte ausführen:

* Einrichten von Berechtigungen für alle Projekte
* Einrichten von Berechtigungen für eine gemeinsame VPC




== Richten Sie Berechtigungen zum Erstellen des Connectors aus BlueXP oder gcloude ein

Bevor Sie einen Connector von BlueXP oder mithilfe von gcloude implementieren können, müssen Sie sicherstellen, dass Ihr Google Cloud Konto die richtigen Berechtigungen besitzt.

.Schritte
. Benutzerdefinierte Rolle in Google Cloud erstellen:
+
.. Erstellen Sie eine YAML-Datei mit den folgenden Berechtigungen:
+
[source, yaml]
----
title: Connector deployment policy
description: Permissions for the user who deploys the Connector from BlueXP
stage: GA
includedPermissions:
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.list
----
.. Aktivieren Sie in Google Cloud die Cloud Shell.
.. Laden Sie die YAML-Datei hoch, die die erforderlichen Berechtigungen enthält.
.. Erstellen Sie mithilfe von eine benutzerdefinierte Rolle `gcloud iam roles create` Befehl.
+
Im folgenden Beispiel wird auf Projektebene eine Rolle namens „connectorDeployment“ erstellt:

+
Gcloud iam-Rollen erstellen connectorDeployment --project=myproject --file=Connector-Deployment.yaml

+
https://["Google Cloud docs: Erstellen und Verwalten benutzerdefinierter Rollen"^]



. Weisen Sie diese benutzerdefinierte Rolle dem Benutzer zu, der den Connector von BlueXP oder über gcloude implementieren wird.
+
https://["Google Cloud docs: Gewähren Sie eine einzige Rolle"^]



.Ergebnis
Der Google Cloud-Nutzer hat jetzt die erforderlichen Berechtigungen zum Erstellen des Connectors.



== Richten Sie die Berechtigungen für den Connector ein

Um dem Connector die erforderlichen Berechtigungen für das Ressourcenmanagement in Google Cloud zu erteilen, ist ein Servicekonto erforderlich. Sie müssen dieses Dienstkonto der Connector VM zuordnen.

.Schritte
. Benutzerdefinierte Rolle in Google Cloud erstellen:
+
.. Erstellen Sie eine YAML-Datei, die den Inhalt des enthält link:reference-permissions-gcp.html["Dienstkontoberechtigungen für den Connector"].
.. Aktivieren Sie in Google Cloud die Cloud Shell.
.. Laden Sie die YAML-Datei hoch, die die erforderlichen Berechtigungen enthält.
.. Erstellen Sie mithilfe von eine benutzerdefinierte Rolle `gcloud iam roles create` Befehl.
+
Im folgenden Beispiel wird auf Projektebene eine Rolle namens „Connector“ erstellt:

+
Gcloud iam-Rollen erstellen Connector --project=myproject --file=Connector.yaml

+
https://["Google Cloud docs: Erstellen und Verwalten benutzerdefinierter Rollen"^]



. Erstellen Sie ein Servicekonto in Google Cloud:
+
.. Klicken Sie im Dienst IAM & Admin auf *Dienstkonten > Service-Konto erstellen*.
.. Geben Sie die Details des Servicekontos ein und klicken Sie auf *Erstellen und Fortfahren*.
.. Wählen Sie die gerade erstellte Rolle aus.
.. Beenden Sie die verbleibenden Schritte, um die Rolle zu erstellen.
+
https://["Google Cloud docs: Erstellen eines Dienstkontos"^]





.Ergebnis
Das Servicekonto für die Connector-VM wird eingerichtet.



== Einrichten von Berechtigungen für alle Projekte

Wenn Sie planen, Cloud Volumes ONTAP-Systeme in verschiedenen Projekten bereitzustellen als das Projekt, in dem sich der Connector befindet, müssen Sie dem Connector-Servicekonto Zugriff auf diese Projekte gewähren.

Nehmen wir beispielsweise an, dass der Connector in Projekt 1 liegt und Sie Cloud Volumes ONTAP-Systeme in Projekt 2 erstellen möchten. Sie müssen in Projekt 2 Zugriff auf das Servicekonto gewähren.

.Schritte
. Wählen Sie in der Google Cloud-Konsole den IAM-Service aus und wählen Sie das Projekt aus, in dem Sie Cloud Volumes ONTAP-Systeme erstellen möchten.
. Wählen Sie auf der *IAM*-Seite *Grant Access* und geben Sie die erforderlichen Details ein.
+
** Geben Sie die E-Mail des Service-Kontos des Connectors ein.
** Wählen Sie die benutzerdefinierte Rolle des Connectors aus.
** Klicken Sie Auf *Speichern*.




Weitere Informationen finden Sie unter https://["Google Cloud-Dokumentation"^]



== Gemeinsame VPC-Berechtigungen einrichten

Wenn Sie ein gemeinsam genutztes VPC verwenden, um Ressourcen in einem Serviceprojekt bereitzustellen, müssen Sie Ihre Berechtigungen vorbereiten.

Diese Tabelle dient als Referenz. Ihre Umgebung sollte nach Abschluss der IAM-Konfiguration die Berechtigungstabelle widerspiegeln.

[cols="10,10,10,20,20,30"]
|===
| Identität | Ersteller | Gehostet in | Berechtigungen für Serviceprojekte | Host-Projektberechtigungen | Zweck 


| Google-Konto zur Bereitstellung des Connectors | Individuell | Service-Projekt  a| 
link:task-set-up-permissions-google.html#set-up-permissions-to-create-the-connector-from-bluexp-or-gcloud["Richtlinie für die Connector-Bereitstellung"]
 a| 
compute.networkUser
| Bereitstellen des Connectors im Serviceprojekt 


| Connector-Servicekonto | Individuell | Service-Projekt  a| 
link:reference-permissions-gcp.html["Kontorichtlinie für Connector-Service"]
 a| 
* compute.networkUser
* Bereitsmanager.Editor

| Implementierung und Wartung von Cloud Volumes ONTAP und Services im Service-Projekt 


| Cloud Volumes ONTAP-Servicekonto | Individuell | Service-Projekt  a| 
* Storage.Administration
* mitglied: BlueXP Dienstkonto als serviceAccount.user

| K. A. | (Optional) für Daten-Tiering sowie Backup und Recovery von BlueXP 


| Google APIs-Serviceagent | Google Cloud | Service-Projekt  a| 
(Standard) Editor
 a| 
compute.networkUser
| Arbeitet im Auftrag der Implementierung mit Google Cloud APIs zusammen. Ermöglicht BlueXP die Nutzung des gemeinsam genutzten Netzwerks. 


| Google Compute Engine Standard-Servicekonto | Google Cloud | Service-Projekt  a| 
(Standard) Editor
 a| 
compute.networkUser
| Implementiert Google Cloud-Instanzen und Computing-Infrastrukturen im Auftrag der Implementierung. Ermöglicht BlueXP die Nutzung des gemeinsam genutzten Netzwerks. 
|===
Hinweise:

. Wenn Sie Firewall-Regeln nicht an die Bereitstellung übergeben und BlueXP diese für Sie erstellen lassen, ist encmentmanager.Editor nur beim Host-Projekt erforderlich. BlueXP erstellt eine Bereitstellung im Hostprojekt, die die VPC0-Firewall-Regel enthält, wenn keine Regel angegeben ist.
. Firewall.create und firewall.delete sind nur erforderlich, wenn Sie Firewall-Regeln nicht an die Bereitstellung übergeben und BlueXP diese für Sie erstellen lassen. Diese Berechtigungen liegen im BlueXP-Konto .yaml-Datei. Wenn Sie ein HA-Paar mithilfe eines gemeinsam genutzten VPC implementieren, werden diese Berechtigungen verwendet, um die Firewall-Regeln für VPC1, 2 und 3 zu erstellen. Für alle anderen Bereitstellungen werden diese Berechtigungen auch verwendet, um Regeln für VPC0 zu erstellen.
. Für das Daten-Tiering muss das Tiering-Servicekonto die serviceAccount.user-Rolle auf dem Servicekonto haben, nicht nur auf Projektebene. Derzeit werden serviceAccount.user auf Projektebene zugewiesen, wenn Sie das Servicekonto mit getIAMPolicy abfragen.

