---
sidebar: sidebar 
permalink: task-provide-permissions-google.html 
keywords: google cloud permissions, permissions, gcp permissions, service account, gcp service account 
summary: Wenn Sie die Connector-Software manuell auf Ihrem eigenen Linux-Host installiert haben, müssen Sie BlueXP mit den zuvor festgelegten Berechtigungen versehen. Durch die Berechtigungen kann BlueXP Ihre Daten- und Storage-Infrastruktur in Google Cloud managen. 
---
= Bereitstellen von Google Cloud-Berechtigungen für BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie die Connector-Software manuell auf Ihrem eigenen Linux-Host installiert haben, müssen Sie BlueXP mit den zuvor festgelegten Berechtigungen versehen. Durch die Berechtigungen kann BlueXP Ihre Daten- und Storage-Infrastruktur in Google Cloud managen.

link:task-set-up-permissions-google.html["Erfahren Sie, wie Sie diese Berechtigungen einrichten"].

Diese Schritte sind nicht anwendbar, wenn Sie den Connector direkt aus BlueXP bereitgestellt haben oder gcloude verwenden.

.Schritte
. Wechseln Sie zum Google Cloud Portal und weisen Sie das Servicekonto der VM-Instanz des Connectors zu.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Google Cloud-Dokumentation: Ändern des Dienstkontos und des Zugriffsumfangs für eine Instanz"^]

. Wenn Sie Ressourcen in anderen Google Cloud-Projekten managen möchten, gewähren Sie Zugriff, indem Sie das Servicekonto mit der BlueXP Rolle zu diesem Projekt hinzufügen. Sie müssen diesen Schritt für jedes Projekt wiederholen.


.Ergebnis
BlueXP verfügt jetzt über die nötigen Berechtigungen, um Aktionen in Google Cloud für Sie durchzuführen.
