= Anschluss 3.9.51
:allow-uri-read: 




=== Anschluss 3.9.51

Diese Version des BlueXP Connector enthält kleinere Sicherheitsverbesserungen und Bug Fixes.

Derzeit ist die Version 3.9.51 für den Standardmodus und den eingeschränkten Modus verfügbar.



=== Identitäts- und Zugriffsmanagement (BlueXP , IAM)

* Nun müssen Sie Benutzern Rollen zuweisen, damit sie Zugriff auf den Ransomware-Schutz haben. Sie können einem Benutzer eine von zwei Rollen zuweisen: Ransomware Protection Admin oder Ransomware Protection Viewer.
* Sie müssen Benutzern nun Rollen zuweisen, damit sie Zugriff auf NetApp Keystone haben. Sie können einem Benutzer eine von zwei Rollen zuweisen: Keystone Admin oder Keystone Viewer.
* Sie können nun ein Keystone Abonnement mit einem IAM-Projekt verknüpfen. Durch die Verknüpfung einer Keystone Subscription mit einem IAM-Projekt können Sie den Zugriff auf Keystone innerhalb von BlueXP  steuern.


link:reference-iam-predefined-roles.html["Informieren Sie sich über die neuen Rollen."^].
