= Anschluss 3.9.51
:allow-uri-read: 




=== Anschluss 3.9.51

Diese Version des BlueXP Connector enthält kleinere Sicherheitsverbesserungen und Bug Fixes.

Derzeit ist die Version 3.9.51 für den Standardmodus und den eingeschränkten Modus verfügbar.



=== Identitäts- und Zugriffsmanagement (BlueXP , IAM)

* Benutzer ohne den Org-Administrator, Ordner- oder Projektadministrator müssen einer Ransomware-Sicherheitsrolle zugewiesen werden, um Zugriff auf Ransomware-Schutz zu haben. Sie können einem Benutzer eine von zwei Rollen zuweisen: Ransomware Protection Admin oder Ransomware Protection Viewer.
* Benutzer ohne Org.-Administrator, Ordner- oder Projektadministrator müssen einer Keystone-Rolle zugewiesen werden, um Zugriff auf Keystone zu haben. Sie können einem Benutzer eine von zwei Rollen zuweisen: Keystone Admin oder Keystone Viewer.


link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über Zugriffsrollen."^]

* Wenn Sie über die Rolle „Org-Administrator“ oder „Ordner“ oder „Projektadministrator“ verfügen, können Sie jetzt ein Keystone-Abonnement mit einem IAM-Projekt verknüpfen. Durch die Verknüpfung einer Keystone Subscription mit einem IAM-Projekt können Sie den Zugriff auf Keystone innerhalb von BlueXP  steuern.

