= Anschluss 3.9.52
:allow-uri-read: 




=== Anschluss 3.9.52

Diese Version des BlueXP -Connectors enthält kleinere Sicherheitsverbesserungen und Fehlerbehebungen sowie einige zusätzliche Updates.

Derzeit ist die Version 3.9.52 für den Standardmodus und den eingeschränkten Modus verfügbar.



==== Unterstützung für Docker 27 und Docker 28

Docker 27 und Docker 28 werden nun vom Connector unterstützt.



==== Cloud Volumes ONTAP

Kapazitätsbasierte Knoten von Cloud Volumes ONTAP werden nicht mehr heruntergefahren, wenn der Connector nicht konform ist oder länger als 14 Tage ausfällt. Cloud Volumes ONTAP sendet weiterhin Event Management-Nachrichten, wenn der Zugriff auf den Connector verloren geht. Diese Änderung soll sicherstellen, dass Cloud Volumes ONTAP auch bei längerem Ausfall des Connectors weiterbetrieben werden kann. Die Compliance-Anforderungen für den Connector bleiben hiervon unberührt.



=== Keystone Administration in BlueXP  verfügbar

Die Beta für NetApp Keystone in BlueXP  hat den Zugriff auf die Keystone Administration hinzugefügt. Sie können die Anmeldeseite für die NetApp Keystone Beta über die linke Navigationsleiste von BlueXP  aufrufen.



=== Identitäts- und Zugriffsmanagement (BlueXP , IAM)

Die folgenden neuen Funktionen sind in BlueXP IAM verfügbar.



==== Multi-Faktor-Authentifizierung (MFA) für lokale Benutzer

Lokale Benutzer (nicht föderiert und nicht mit einem NetApp Support Site-Konto verknüpft) können die Multi-Faktor-Authentifizierung aktivieren. Administratoren können die MFA-Einstellungen der Benutzer verwalten, z. B. vorübergehend deaktivieren oder bei Bedarf entfernen.
