= 
:allow-uri-read: 


Erstellen Sie eine Rolle und wenden Sie sie auf ein Servicekonto an, das Sie für die VM-Instanz des Connectors verwenden werden.

.Schritte
. Benutzerdefinierte Rolle in Google Cloud erstellen:
+
.. Erstellen Sie eine YAML-Datei, die die in definierten Berechtigungen enthält link:reference-permissions-gcp.html["Connector-Richtlinie für Google Cloud"].
.. Aktivieren Sie in Google Cloud die Cloud Shell.
.. Laden Sie die YAML-Datei hoch, die die erforderlichen Berechtigungen für den Connector enthält.
.. Erstellen Sie mithilfe von eine benutzerdefinierte Rolle `gcloud iam roles create` Befehl.
+
Im folgenden Beispiel wird auf Projektebene eine Rolle namens „Connector“ erstellt:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud docs: Erstellen und Verwalten benutzerdefinierter Rollen"^]



. Erstellen Sie ein Servicekonto in Google Cloud:
+
.. Klicken Sie im Dienst IAM & Admin auf *Dienstkonten > Service-Konto erstellen*.
.. Geben Sie die Details des Servicekontos ein und klicken Sie auf *Erstellen und Fortfahren*.
.. Wählen Sie die gerade erstellte Rolle aus.
.. Beenden Sie die verbleibenden Schritte, um die Rolle zu erstellen.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud docs: Erstellen eines Dienstkontos"^]





.Ergebnis
Sie verfügen jetzt über ein Servicekonto, das Sie der VM-Instanz des Connectors zuweisen können.
