= 
:allow-uri-read: 


Je nach Betriebssystem ist entweder Podman oder Docker Engine erforderlich, bevor Sie den Connector installieren.

* Podman ist für Red hat Enterprise Linux 8 und 9 erforderlich.
* Die Docker Engine ist für Ubuntu, CentOS und Red hat Enterprise Linux 7 erforderlich.


.Schritte
[role="tabbed-block"]
====
.Podman
--
Installieren Sie Podman 4.6.1.

.Schritte
. Entfernen Sie das Paket podman-Docker, wenn es auf dem Host installiert ist.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Installieren Sie Podman.
+
Podman ist über die offiziellen Red hat Enterprise Linux-Repositorys erhältlich.

+
[source, cli]
----
sudo dnf install podman-2:4.6.1
----
. Aktivieren und starten Sie den podman.Socket-Dienst.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Installieren Sie Python3.
+
[source, cli]
----
sudo dnf install python3
----
. Installieren Sie das EPEL Repository-Paket, wenn es nicht bereits auf Ihrem System verfügbar ist.
+
Dieser Schritt ist erforderlich, da podman-compose im Repository Extra Packages for Enterprise Linux (EPEL) verfügbar ist.

+
Für Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Für Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. Installieren Sie das Paket „podman-compose“ 1.0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: Verwenden der `dnf install` Befehl erfüllt die Anforderung zum Hinzufügen von podman-compose zur Umgebungsvariable PATH. Der Installationsbefehl fügt podman-compose zu /usr/bin hinzu, das bereits im enthalten ist `secure_path` Option auf dem Host.



--
.Docker Engine
--
Installieren Sie eine Version der Docker Engine zwischen 19.3.1 und 25.0.5.

.Schritte
. Installieren Sie Die Docker Engine.
+
https://docs.docker.com/engine/install/["Installationsanweisungen von Docker anzeigen"^]

+
Befolgen Sie die Schritte, um eine bestimmte Version der Docker Engine zu installieren. Durch die Installation der neuesten Version wird eine Docker Version installiert, die BlueXP nicht unterstützt.

. Docker muss aktiviert und ausgeführt werden.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====